"""Render shared health rules. Use --check to detect drift."""

import argparse
import json
from pathlib import Path

from mdp_functions.health_policy import (
    CANARY_HTTP_GRACE_S,
    CANARY_TIMEOUT_S,
    COVERAGE_DEFAULT,
    cadence_overdue_sql,
    scheduled_cycle_sql,
)

# Viewer display allows normal collection delays. Cadence alerts keep their own
# unchanged deadline in mdp_functions.health_policy.
READER_FRESHNESS = {
    "hourly": {"period_seconds": 3600, "grace_seconds": 1800},
    "daily": {"period_seconds": 86400, "grace_seconds": 10800},
    "weekly": {"period_seconds": 604800, "grace_seconds": 43200},
}

ROOT = Path(__file__).resolve().parents[2]
PYTHON_OUTPUT = ROOT / "functions/src/mdp_functions/health_policy_generated.py"
DBT_OUTPUT = ROOT / "dbt/macros/mdp_health_policy.sql"
OUTPUT = ROOT / "control/packages/contracts/src/health-policy.generated.ts"
API_OUTPUT = ROOT / "control/apps/control-api/src/health-policy.generated.ts"
API_EXPORT = (
    "// Generated by ops/ci/generate_health_policy.py. Do not edit.\n"
    'export * from "@mdp/contracts/health-policy.generated";\n'
)


def render() -> str:
    return (
        "// Generated by ops/ci/generate_health_policy.py. Do not edit.\n"
        f"export const readerFreshness = {json.dumps(READER_FRESHNESS, indent=2)} as const;\n\n"
        f"export const canaryTimeoutMs = {CANARY_TIMEOUT_S * 1000};\n"
        f"export const canaryHttpTimeoutMs = canaryTimeoutMs + {CANARY_HTTP_GRACE_S * 1000};\n"
        f"const coverageDefault = {json.dumps(COVERAGE_DEFAULT)} as const;\n"
        "export function defaultCoverageFloor(total: number): number {\n"
        "  return total >= coverageDefault.large_set_size\n"
        "    ? coverageDefault.large_set_floor : coverageDefault.small_set_floor;\n"
        "}\n\n"
        "export function cadenceOverdueSql(column: 'cadence' | 'c.cadence'): string {\n"
        f"  return {json.dumps(cadence_overdue_sql('{cadence}'))}.replace('{{cadence}}', column);\n"
        "}\n\n"
        "export function scheduledCycleSql(column: 'opened_by_dbt_run_id' | 'c.opened_by_dbt_run_id' = 'opened_by_dbt_run_id'): string {\n"
        f"  return {json.dumps(scheduled_cycle_sql('{opener}'))}.replaceAll('{{opener}}', column);\n"
        "}\n"
    )


def render_python() -> str:
    return (
        "# Generated by ops/ci/generate_health_policy.py. Do not edit.\n"
        f"READER_FRESHNESS = {json.dumps(READER_FRESHNESS, indent=4)}\n"
    )


def render_dbt() -> str:
    return (
        "{# Generated by ops/ci/generate_health_policy.py. Do not edit. #}\n"
        "{% macro mdp_scheduled_cycle(column) -%}\n"
        + scheduled_cycle_sql("{{ column }}")
        + "\n{%- endmacro %}\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    command = "uv run --project functions python ops/ci/generate_health_policy.py"
    if args.check:
        if any(
            not path.exists() or path.read_text() != rendered
            for path, rendered in (
                (OUTPUT, content),
                (API_OUTPUT, API_EXPORT),
                (DBT_OUTPUT, render_dbt()),
                (PYTHON_OUTPUT, render_python()),
            )
        ):
            raise SystemExit(f"Health rules are stale. Run {command}.")
        print(
            f"PASS health rules are current. Run {command} after changing a health policy input."
        )
    else:
        OUTPUT.write_text(content)
        API_OUTPUT.write_text(API_EXPORT)
        DBT_OUTPUT.write_text(render_dbt())
        PYTHON_OUTPUT.write_text(render_python())
        print(f"Health rules generated. Run {command} --check to verify them.")


if __name__ == "__main__":
    main()
