"""Render the shared sandbox policy for SQL, TypeScript, R and the analyst guide."""

import json
from pathlib import Path

from mdp_functions.sandbox_policy import POLICY

ROOT = Path(__file__).resolve().parents[2]


def render(check=False):
    blob = json.dumps(POLICY, indent=2, ensure_ascii=False) + "\n"
    outputs = {
        ROOT / "control/apps/control-api/src/sandbox-policy.json": blob,
        ROOT / "control/packages/data-sdk/src/sandbox-policy.generated.ts": "// Generated by ops/ci/generate_sandbox_policy.py. Do not edit.\nexport const sandboxPolicy = "+blob.strip()+" as const;\n",
    }
    p = ROOT / "r/mdpr/inst/extdata/contracts.json"
    contracts = json.loads(p.read_text())
    contracts["sandbox"] = POLICY
    outputs[p] = json.dumps(contracts, indent=2, ensure_ascii=False) + "\n"
    sql = ROOT / "ops/fly/postgres/boot/init/10-warehouse-grants.sql"
    text = sql.read_text()
    start, end = "-- sandbox-policy:start", "-- sandbox-policy:end"
    generated = f"{start}\n-- Generated by ops/ci/generate_sandbox_policy.py.\nCREATE OR REPLACE FUNCTION mdp.sandbox_policy() RETURNS jsonb\nLANGUAGE sql IMMUTABLE SET search_path=pg_catalog AS $policy$ SELECT $json${json.dumps(POLICY, ensure_ascii=False)}$json$::jsonb $policy$;\nREVOKE ALL ON FUNCTION mdp.sandbox_policy() FROM PUBLIC,service_read;\nCREATE OR REPLACE FUNCTION mdp.is_sandbox(schema_name text) RETURNS boolean LANGUAGE sql IMMUTABLE SET search_path=pg_catalog AS $predicate$ SELECT starts_with(schema_name, mdp.sandbox_policy()->>'prefix') $predicate$;\nREVOKE ALL ON FUNCTION mdp.is_sandbox(text) FROM PUBLIC,service_read;\n{end}"
    if start in text:
        before, rest = text.split(start)
        _, after = rest.split(end)
        text = before + generated + after
    else:
        text = text.replace(
            "CREATE SCHEMA IF NOT EXISTS mdp;",
            "CREATE SCHEMA IF NOT EXISTS mdp;\n" + generated,
        )
    outputs[sql] = text
    p = ROOT / "docs/analyst-access.md"
    text = p.read_text()
    start, end = "<!-- sandbox-policy:start -->", "<!-- sandbox-policy:end -->"
    generated = f"{start}\nEach login has {POLICY['connection_limit']} connections, a {POLICY['statement_timeout']} statement timeout, a {POLICY['idle_in_transaction_session_timeout']} idle transaction timeout, and a {POLICY['temp_file_limit']} temporary-file limit.\nA sandbox has a {POLICY['quota_bytes'] // (1024**3)} GiB creation quota. The checker runs every {POLICY['poll_seconds']} seconds and alerts at {int(POLICY['warn_fraction'] * 100)} percent.\nAt the quota it freezes new objects; existing tables can still be read or reduced. Delete unused tables and check status to resume creation.\nArchives live under `{POLICY['archive_root']}/<schema>/<timestamp>/`. Open the manifest before removing a local archive.\n{end}"
    if start in text:
        before, rest = text.split(start)
        _, after = rest.split(end)
        text = before + generated + after
    else:
        text = text.replace(
            "## Keep your analysis", "## Keep your analysis\n\n" + generated
        )
    outputs[p] = text
    for path, value in outputs.items():
        if check:
            assert path.read_text() == value, (
                f"{path.relative_to(ROOT)} is stale; run uv run --project functions python ops/ci/generate_sandbox_policy.py"
            )
        else:
            path.write_text(value)


if __name__ == "__main__":
    import sys

    render("--check" in sys.argv)
