# Generated by ops/ci/generate_health_policy.py. Do not edit.
READER_FRESHNESS = {
    "hourly": {
        "period_seconds": 3600,
        "grace_seconds": 1800
    },
    "daily": {
        "period_seconds": 86400,
        "grace_seconds": 10800
    },
    "weekly": {
        "period_seconds": 604800,
        "grace_seconds": 43200
    }
}
