"""Conservative scope name matching, shared by collectors and dbt.

ASCII letters ignore case and Unicode whitespace collapses to one space. Other
characters stay distinct: punctuation, accents, full-width letters and sharp s.
A name is a fallback hint, so this rule avoids inventing extra name equivalences.
"""

import string

# Unicode White_Space plus the four separators Python treats as whitespace.
WHITESPACE = (
    " \t\n\r\v\f\x1c\x1d\x1e\x1f\x85\xa0\u1680"
    + "".join(chr(code) for code in range(0x2000, 0x200B))
    + "\u2028\u2029\u202f\u205f\u3000"
)
FROM = string.ascii_uppercase + WHITESPACE
TO = string.ascii_lowercase + " " * len(WHITESPACE)
TRANSLATION = str.maketrans(FROM, TO)


def fold(name: str) -> str:
    """For example, ``'  MIX\\tTape  '`` becomes ``'mix tape'``."""
    return " ".join(part for part in name.translate(TRANSLATION).split(" ") if part)


def sql(expression: str) -> str:
    """Render the same translation and space collapse for PostgreSQL and DuckDB."""
    source = " || ".join(f"chr({ord(char)})" for char in FROM)
    return f"trim(regexp_replace(translate({expression}, {source}, '{TO}'), ' +', ' ', 'g'))"


def dbt_macros() -> str:
    """Generated by ``mdp sources export`` alongside the owner rules."""
    return (
        "{# Generated by `mdp sources export` from mdp_functions/name_folding.py; do not edit. #}\n"
        "\n{% macro mdp_fold_name(expression) -%}\n"
        + sql("{{ expression }}")
        + "\n{%- endmacro %}\n"
    )
