"""Runbook configuration installed by the configuration owner, never functions_rt."""

from typing import Any

from mdp_functions.errors import error_hint
from mdp_functions.sandbox_policy import POLICY

RUNBOOKS = {
    **POLICY["messages"],
    "showcase_inventory_failed": error_hint("showcase_inventory_failed")["next_step"],
    "source_unregistered": error_hint("source_unregistered")["next_step"],
    "target_zero_yield": error_hint("target_zero_yield")["next_step"],
    "undeclared_exclusion": error_hint("undeclared_exclusion")["next_step"],
    "provider_credentials_missing": error_hint("provider_credentials_missing")["next_step"],
    "forbidden": "Staff opens console read and analysis pages; operator actions need admin. Ask an operator for a staff key with `pnpm --dir control mdp keys create --role staff --label <text>`; see docs/operating.md#reach-control-api.",
    "invalid_row_coverage": "Set min_row_coverage above 0 and at most 1, then run uv run --project functions mdp sources export.",
    "invalid_target_coverage": "Use a min_target_coverage fraction above 0 and at most 1 on a target-set source or bronze endpoint, then test with fixtures.",
    "invalid_stale_cycles": "Use a positive whole number for stale_target_cycles.",
    "source_canary_failed": "Inspect the failed or timed-out sample audit; not-due and skipped sources open no alert; see [source_canary_failed](ops/runbooks/source_canary_failed.md).",

    "jev_egress_refused": "Use declared public fields in a global gold run. Tenant and personal-data opt-ins are absent; see docs/jev.md.",
    "jev_fixture_miss": "Record the missing question-version and state pair after owner setup with mdp jev record; see docs/jev.md. Never substitute synthetic answers for live evidence.",
    "jev_layer_refused": "Move the decision into @gold(provider='typesafe', llm_step=...). Bronze only fetches; see docs/jev.md.",
    "jev_state_invalid": "Supply each declared state field from the current input row as a scalar value and stay within the size limit; see docs/jev.md.",
    "jev_unavailable": "Check the configured proxy or TypeSafe account and provider status. Invalid responses and failed calls retain their reservation; see docs/jev.md.",
    "export_spec_missing": "Recover the frozen historical specification from immutable raw.targets using ops/fly/backfill-export-specs.py; never use live targets.",
    "proxy_unavailable": "Restore the configured Webshare credentials or provider service; do not switch routes after a block.",
    "proxy_market_required": "Set the frozen target's market or storefront before explicitly selecting residential transport.",
    "invalid_transport": "Use direct or residential in the manifest or transport override.",
    "scrape_blocked": "Stop this host; review its signature and public surface. Never change exits, tier or user agent to retry a block. See [scrape_blocked](ops/runbooks/scrape_blocked.md).",
    "surface_drift": "Three targets missed an envelope (a gold function: three inputs in a row, none rejected before, with no parsed input between). Review reconnaissance and parser before enabling the paused streamline; a gold input that misses again after that is its own failure and parks. See [surface_drift](ops/runbooks/surface_drift.md).",
    "envelope_mismatch": "Inspect the frozen target and expected path, then repair the parser.",
    "proxy_quota_exhausted": "Review provider budget or subscription; market targets pause while direct continues.",
    "stale_target": "A 404 or 410 warns once. Parking needs healthy peers on the same host and stays within the per-cycle cap.",
    "egress_blocked": "Silver cannot open sockets; remove network calls from the function.",
    "undeclared_read": "Declare each relation in reads before invocation.",
    "llm_budget_exceeded": "Review the per-step reservation and hard action before rerunning.",
    "litellm_unavailable": "Restore the model proxy URL and key alias; retain input dumps.",
    "input_identity_missing": "Apply mdp_input_identity to the gold input relation.",
    "cycle_not_closed": "Rerun the full cadence job so its close returns after the mirror catch-up; see [cycle_not_closed](ops/runbooks/cycle_not_closed.md).",
    "cadence_failed": "A runner failed or a cycle exceeded its cadence interval; inspect the failing model and retry the cycle; see [cadence_failed](ops/runbooks/cadence_failed.md).",
    "cycle_not_found": "Check the cycle identifier and immutable dbt binding before closing; see [cycle_not_found](ops/runbooks/cycle_not_found.md).",
    "scope_mismatch": "Compare the invocation with its bound scope, cadence, runner and cycle state; see [scope_mismatch](ops/runbooks/scope_mismatch.md).",
    "warehouse_unavailable": "Check warehouse health and committed receipts, then retry the same close or failed built-in attempt; see [warehouse_unavailable](ops/runbooks/warehouse_unavailable.md).",
    "control_db_unavailable": "Restore control database connectivity before retrying or admitting work; see [control_db_unavailable](ops/runbooks/control_db_unavailable.md).",
    "vendor_4xx": "Inspect the vendor response and target identity; correct the request before retrying.",
    "vendor_retryable": "Inspect the call ledger and provider availability; request a fresh attempt when the provider recovers.",
    "accounting_mismatch": "Compare observed, yielded and rejected page counts; correct source accounting before retrying.",
    "schema_drift": "Review the archived schema fingerprint and added or widened nullable columns.",
    "schema_breaking": "Inspect the retained page and schema fingerprint; correct the schema or source values before repair.",
    "dump_unreadable": "Inspect the referenced manifest and parts; restore valid retained objects before requesting repair.",
    "dump_late": "Inspect batch attempt and lease ownership; quarantine stale output and resume only through the current attempt.",
    "invoke_timeout": "Inspect committed pages and the deadline; a caller may request a new attempt to resume remaining work.",
    "time_budget": error_hint("time_budget")["next_step"],
    "service_unreachable": "Check authenticated health, network reachability and service configuration before retrying.",
    "partial_coverage": "Compare eligible target coverage with its floor, then inspect rejected rows and loads. Zero delivery of expected work fails.",
    "cost_cap_hit": "Review budget reservations with the configuration owner before resuming paid work. A vendor provider's request cap (cap_requests on its provider budget, 24.5) stops new calls at the cap for the period, and a function naming a provider with no budget row, or a row without cap_requests or hard_action pause, fails closed; see [cost_cap_hit](ops/runbooks/cost_cap_hit.md).",
    "cost_cap_soft": "A vendor provider's requests this period passed its budget's soft_pct of cap_requests; one alert per period. Check the run cadence and the contract allotment before the cap stops calls; see [cost_cap_hit](ops/runbooks/cost_cap_hit.md).",
    "undeclared_write": "Correct the function writes declaration or emitted table; inspect the retained failed page.",
    "undeclared_egress": "Correct the function external declaration or remove the undeclared request.",
    "forbidden_path": "A request reached the runtime forbidden-path list and was refused at the transport; change the collector, never the list; see [forbidden_path](ops/runbooks/forbidden_path.md).",
    "invalid_output_key": "Output key columns must be present and unique per input and table; correct the function body before rerunning.",
    "config_unresolved": "The run predates its frozen configuration; admit a new run instead of retrying it.",
    "llm_config_invalid": "Correct the llm_step configuration row the run resolved before rerunning.",
    "llm_step_missing": "Create or enable the llm_step the function declares before rerunning.",
    "function_failed": "Inspect the function exception, trace and retained page; correct the source before retrying.",
    "control_api_unavailable": "A promoter could not reach control-api or was refused: check mdp-control-api health and MDP_CONTROL_API_URL and MDP_CONTROL_API_KEY on mdp-functions, then request a fresh attempt. See [control_api_unavailable](ops/runbooks/control_api_unavailable.md).",
    "inputs_parked": "Inputs this function rejected on their own in its `park_after` count of runs within 28 days (a 404, a record it could not read, a non-429 4xx) sit out its read; the run's inputs_parked event lists them. Fix the cause, then release them from the function page or with `pnpm mdp unpark <key>` (it resolves this alert); otherwise they return after 28 days. A drift streak and vendor outages never park an input; a single track's envelope miss among parsed ones does. See [inputs_parked](ops/runbooks/inputs_parked.md).",
    "target_held": "Another writer holds this target (a seed, a spec, or a person's deactivation); the promoter leaves it as it is.",
    "fixture_miss": "Add the missing exact request response fixture or correct the fixture request.",
    "reference_generation_incomplete": "Reference staging keeps the last complete generation; resume the missing mb_spine landings, or re-land a pruned generation before a Replay; see [reference_generation_incomplete](ops/runbooks/reference_generation_incomplete.md).",
    "reference_disk_high": "The mirror volume passed 80%: imports pause until it is expanded; see [reference_disk_high](ops/runbooks/reference_disk_high.md).",
    "reference_dump_stale": "No newer MusicBrainz dump landed within its cadence; see [reference_dump_stale](ops/runbooks/reference_dump_stale.md).",
    "reference_import_failed": "The mirror import failed or did not validate; the serving generation is unchanged; see [reference_import_failed](ops/runbooks/reference_import_failed.md).",
    "warehouse_disk_high": "An mb_spine landing would pass 60% of the pgdata volume: it stopped and landed nothing; see [warehouse_disk_high](ops/runbooks/warehouse_disk_high.md).",
    "retention_failed": "The hourly retention sweep failed for this function, so text a person wrote may outlive its retain_days: read the functions service's retention_failed log line, fix the cause (object store or warehouse access), and confirm the next sweep deletes what is due before resolving; see docs/operating.md (Retention).",
    "spine_narrowing_due": "A spine generation's projected write passed 30% of the pgdata volume, or the tracked recordings passed 100k: ship the narrowed release step before the next import; see [spine_narrowing_due](ops/runbooks/spine_narrowing_due.md).",
    "cursor_conflict": "Inspect cursor version and reset generation; resume from the current checkpoint.",
    "invalid_function": "Provide an async function or async generator matching the function contract.",
    "not_implemented": "This execution layer is unavailable until its implementation is deployed.",
    "variant_mismatch": "A proxy_country knob disagrees with the target's frozen market; align the knob with the market, or export a new variant, never the reverse.",
    "dbt_failure": "A dbt Cloud job run failed; read its run logs in dbt Cloud, fix the model, and rerun the job.",
    "dbt_api_unavailable": "The dbt Cloud API could not verify the run's identity; check the dbt Cloud token and API reachability, then retry the bind.",
    "core_run_in_progress": "A Core run of this cadence and scope holds its lock; no cycle was bound. Run again once it finishes.",
    "global_inputs_mismatch": "The bind's global inputs differ from control.dbt_job; deploy the runner with the current graph, or correct the job row.",
    "runner_inactive": "The binding runner is not the one control.runner_mode names; bind through the active runner or switch the mode.",
    "runner_outdated": "The run was bound through a pre-stamp dbt hook; deploy the current core-runner image and rerun the cadence. See [runner_outdated](ops/runbooks/runner_outdated.md).",
    "scheduled_only_refused": "This function freezes rows only in a scheduled cycle; manual and backfill admissions are refused. Retries and Replays attached to a scheduled cycle pass this service gate; tenant Replay is separately unavailable. See [scheduled_only_refused](ops/runbooks/scheduled_only_refused.md).",
    "backfill_window_refused": "A KEXP backfill window covers at most one airdate year within the last two years; split the window by year and admit each.",
    "replay_refused": "A Replay needs a closed cycle in its cadence and scope, and membership freezes only on an open cycle; pick a closed cycle or bind a new one.",
    "object_store_unavailable": "Object storage is unreachable; check the bucket endpoint and credentials, then retry.",
    "invalid_request": "The request was malformed; correct it and send it again.",
    "invalid_work_key": "The transport work key does not match the run's frozen inputs; resend with the key admission returned.",
    "unknown_run": "No run has this id; check the id.",
    "unknown_source": "No function is registered under this source key; check the key or deploy the function.",
}


def seed_runbooks(conn: Any) -> None:
    for kind, body in RUNBOOKS.items():
        conn.execute(
            "INSERT INTO control.runbook(slug,title,body_md) VALUES (%s,%s,%s) ON CONFLICT(slug) DO NOTHING",
            (kind.replace("_", "-"), kind.replace("_", " "), body),
        )
