// Generated by ops/ci/generate_health_policy.py. Do not edit.
export const readerFreshness = {
  "hourly": {
    "period_seconds": 3600,
    "grace_seconds": 1800
  },
  "daily": {
    "period_seconds": 86400,
    "grace_seconds": 10800
  },
  "weekly": {
    "period_seconds": 604800,
    "grace_seconds": 43200
  }
} as const;

export const canaryTimeoutMs = 25000;
export const canaryHttpTimeoutMs = canaryTimeoutMs + 5000;
const coverageDefault = {"large_set_size": 10, "large_set_floor": 0.9, "small_set_floor": 1.0} as const;
export function defaultCoverageFloor(total: number): number {
  return total >= coverageDefault.large_set_size
    ? coverageDefault.large_set_floor : coverageDefault.small_set_floor;
}

export function cadenceOverdueSql(column: 'cadence' | 'c.cadence'): string {
  return "CASE {cadence} WHEN 'hourly' THEN interval '1 hour' WHEN 'daily' THEN interval '1 day' WHEN 'weekly' THEN interval '7 days' ELSE interval '7 days' END".replace('{cadence}', column);
}

export function scheduledCycleSql(column: 'opened_by_dbt_run_id' | 'c.opened_by_dbt_run_id' = 'opened_by_dbt_run_id'): string {
  return "left({opener}, 7) <> 'manual:' AND left({opener}, 9) <> 'backfill:' AND left({opener}, 7) <> 'canary:'".replaceAll('{opener}', column);
}
