// Shared mark facts. File names resolve under /brand/third-party/.
export type MarkTone = "dark" | "light";
export type MarkDefinition = {
  label: string;
  href: string;
  owner: string;
  rule: string;
  source_url: string;
  changed: string | null;
  files: { onDark?: string; onLight?: string };
  plate: "light" | "dark" | null;
  monogram: string | null;
};
const appleMusic: MarkDefinition = {
  label: "Apple Music",
  href: "https://music.apple.com",
  owner: "Apple",
  rule: "Apple trademark guidelines https://www.apple.com/legal/intellectual-property/guidelinesfor3rdparties.html",
  source_url: "https://svgl.app/library/apple-music-icon.svg",
  changed: "minified with svgo; otherwise unchanged",
  files: {
    onDark: "apple_music.svg",
    onLight: "apple_music.svg",
  },
  plate: null,
  monogram: null,
};

export const marks: Record<string, MarkDefinition> = {
  apple_music: appleMusic,
  apple_catalog: { ...appleMusic, label: "Apple catalog" },
  spotify: {
    label: "Spotify",
    href: "https://open.spotify.com",
    owner: "Spotify",
    rule: "At least 21 px; white on dark, green on light; linked to Spotify. https://developer.spotify.com/documentation/design",
    source_url:
      "https://developer.spotify.com/images/guidelines/design/2024-spotify-logo-icon.zip",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "spotify-dark.svg",
      onLight: "spotify-light.svg",
    },
    plate: null,
    monogram: null,
  },
  shazam: {
    label: "Shazam",
    href: "https://www.shazam.com",
    owner: "Apple",
    rule: "Apple trademark guidelines https://www.apple.com/legal/intellectual-property/guidelinesfor3rdparties.html",
    source_url:
      "https://assets.shazam.com/website/images/favicons/favicon-32x32",
    changed: null,
    files: {
      onDark: "shazam.png",
      onLight: "shazam.png",
    },
    plate: null,
    monogram: null,
  },
  musicbrainz: {
    label: "MusicBrainz",
    href: "https://musicbrainz.org",
    owner: "MetaBrainz",
    rule: "CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/",
    source_url:
      "https://github.com/metabrainz/design-system/tree/master/brand/logos/MusicBrainz/SVG",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "musicbrainz.svg",
      onLight: "musicbrainz.svg",
    },
    plate: null,
    monogram: null,
  },
  listenbrainz: {
    label: "ListenBrainz",
    href: "https://listenbrainz.org",
    owner: "MetaBrainz",
    rule: "CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/",
    source_url:
      "https://github.com/metabrainz/design-system/tree/master/brand/logos/ListenBrainz/SVG",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "listenbrainz.svg",
      onLight: "listenbrainz.svg",
    },
    plate: null,
    monogram: null,
  },
  wikipedia: {
    label: "Wikipedia",
    href: "https://www.wikipedia.org",
    owner: "Wikimedia Foundation",
    rule: "CC BY-SA 3.0 https://creativecommons.org/licenses/by-sa/3.0/ ; WMF trademark policy https://foundation.wikimedia.org/wiki/Policy:Trademark_policy",
    source_url: "https://commons.wikimedia.org/wiki/File:Wikipedia-logo-v2.svg",
    changed: "rasterized to a 96 px PNG; otherwise unchanged",
    files: {
      onDark: "wikipedia.png",
      onLight: "wikipedia.png",
    },
    plate: null,
    monogram: null,
  },
  deezer: {
    label: "Deezer",
    href: "https://www.deezer.com",
    owner: "Deezer",
    rule: "Deezer brand guidelines https://www.deezerbrand.com/",
    source_url: "https://media.ffycdn.net/eu/deezer/fWVrZctigy7YRqgUp1My.png",
    changed: "resized to a 96 px PNG; otherwise unchanged",
    files: {
      onDark: "deezer.png",
      onLight: "deezer.png",
    },
    plate: null,
    monogram: null,
  },
  billboard: {
    label: "Billboard",
    href: "https://www.billboard.com/charts/hot-100/",
    owner: "Billboard",
    rule: "Signed-in factual identification. No affiliation with the companies shown. https://www.billboard.com/terms-of-use/",
    source_url: "https://www.billboard.com",
    changed:
      "minified with svgo; otherwise unchanged; original glyph from simple-icons (CC0)",
    files: {
      onDark: "billboard.svg",
    },
    plate: "light",
    monogram: "Billboard",
  },
  youtube: {
    label: "YouTube",
    href: "https://www.youtube.com",
    owner: "Google",
    rule: "YouTube brand rules https://www.youtube.com/howyoutubeworks/resources/brand-resources/",
    source_url: "https://svgl.app/library/youtube.svg",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "youtube.svg",
      onLight: "youtube.svg",
    },
    plate: null,
    monogram: null,
  },
  soundcloud: {
    label: "SoundCloud",
    href: "https://soundcloud.com",
    owner: "SoundCloud",
    rule: "SoundCloud trademark rules https://soundcloud.com/pages/trademark",
    source_url: "https://svgl.app/library/soundcloud-logo.svg",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "soundcloud-dark.svg",
      onLight: "soundcloud-light.svg",
    },
    plate: null,
    monogram: null,
  },
  bandcamp: {
    label: "Bandcamp",
    href: "https://bandcamp.com",
    owner: "Bandcamp",
    rule: "Bandcamp trademark terms https://bandcamp.com/terms_of_use",
    source_url: "https://s4.bcbits.com/img/favicon/favicon-32x32.png",
    changed: null,
    files: {
      onDark: "bandcamp.png",
      onLight: "bandcamp.png",
    },
    plate: null,
    monogram: null,
  },
  postgresql: {
    label: "PostgreSQL",
    href: "https://www.postgresql.org",
    owner: "PostgreSQL Community Association of Canada",
    rule: "PostgreSQL trademark policy https://www.postgresql.org/about/policies/trademarks/",
    source_url:
      "https://wiki.postgresql.org/images/a/a4/PostgreSQL_logo.3colors.svg",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "postgresql.svg",
      onLight: "postgresql.svg",
    },
    plate: null,
    monogram: null,
  },
  r: {
    label: "R",
    href: "https://www.r-project.org",
    owner: "R Foundation",
    rule: "CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/",
    source_url: "https://www.r-project.org/logo/Rlogo.svg",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "r.svg",
      onLight: "r.svg",
    },
    plate: null,
    monogram: null,
  },
  python: {
    label: "Python",
    href: "https://www.python.org",
    owner: "Python Software Foundation",
    rule: "Python trademark policy https://www.python.org/psf/trademarks/",
    source_url: "https://svgl.app/library/python.svg",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "python.svg",
      onLight: "python.svg",
    },
    plate: null,
    monogram: null,
  },
  fly: {
    label: "Fly.io",
    href: "https://fly.io",
    owner: "Fly.io",
    rule: "Signed-in factual identification. No affiliation with the companies shown. https://fly.io/docs/about/brand/",
    source_url: "https://svgl.app/library/fly.svg",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "fly.svg",
      onLight: "fly.svg",
    },
    plate: null,
    monogram: null,
  },
  litellm: {
    label: "LiteLLM",
    href: "https://www.litellm.ai",
    owner: "LiteLLM",
    rule: "Signed-in factual identification; no published mark license. https://www.litellm.ai",
    source_url:
      "https://cdn.prod.website-files.com/69eb241da3f923869c226875/69f4ac0558833d682c4e6807_favicon_docs_litellm_ai_256x256.png",
    changed: null,
    files: {
      onDark: "litellm.png",
      onLight: "litellm.png",
    },
    plate: null,
    monogram: null,
  },
  clerk: {
    label: "Clerk",
    href: "https://clerk.com",
    owner: "Clerk",
    rule: "Clerk brand assets https://clerk.com/brand-assets",
    source_url: "https://clerk.com/v2/downloads/symbol-light.svg",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "clerk.svg",
      onLight: "clerk.svg",
    },
    plate: "dark",
    monogram: null,
  },
  hono: {
    label: "Hono",
    href: "https://hono.dev",
    owner: "Hono project",
    rule: "MIT https://github.com/honojs/hono/blob/main/LICENSE",
    source_url:
      "https://raw.githubusercontent.com/honojs/hono/main/docs/images/hono-logo.svg",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "hono.svg",
      onLight: "hono.svg",
    },
    plate: null,
    monogram: null,
  },
  nextjs: {
    label: "Next.js",
    href: "https://nextjs.org",
    owner: "Vercel",
    rule: "Vercel brand guidelines https://vercel.com/geist/brands",
    source_url: "https://svgl.app/library/nextjs_icon_dark.svg",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "nextjs.svg",
      onLight: "nextjs.svg",
    },
    plate: "light",
    monogram: null,
  },
  typesafe: {
    label: "TypeSafe AI",
    href: "https://typesafe.ai",
    owner: "TypeSafe AI",
    rule: "Signed-in factual identification; no published mark license. https://typesafe.ai/",
    source_url: "https://svgl.app/library/typesafe-ai-light.svg",
    changed: "minified with svgo; otherwise unchanged",
    files: {
      onDark: "typesafe-dark.svg",
      onLight: "typesafe-light.svg",
    },
    plate: null,
    monogram: null,
  },




  kexp: {
    label: "KEXP",
    href: "https://www.kexp.org",
    owner: "KEXP",
    rule: "Text identification only; no provider logo.",
    source_url: "https://www.kexp.org",
    changed: null,
    files: {},
    plate: null,
    monogram: "KEXP",
  },
  duckdb: {
    label: "DuckDB",
    href: "https://duckdb.org",
    owner: "DuckDB Foundation",
    rule: "Text identification only; no provider logo.",
    source_url: "https://duckdb.org",
    changed: null,
    files: {},
    plate: null,
    monogram: "DuckDB",
  },
  rstudio: {
    label: "RStudio",
    href: "https://posit.co",
    owner: "Posit",
    rule: "Text identification only; no provider logo.",
    source_url: "https://posit.co",
    changed: null,
    files: {},
    plate: null,
    monogram: "RStudio",
  },
  dbeaver: {
    label: "DBeaver",
    href: "https://dbeaver.io",
    owner: "DBeaver",
    rule: "Text identification only; no provider logo.",
    source_url: "https://dbeaver.io",
    changed: null,
    files: {},
    plate: null,
    monogram: "DBeaver",
  },
  jupyter: {
    label: "Jupyter",
    href: "https://jupyter.org",
    owner: "Project Jupyter",
    rule: "Text identification only; no provider logo.",
    source_url: "https://jupyter.org",
    changed: null,
    files: {},
    plate: null,
    monogram: "Jupyter",
  },
  github: {
    label: "GitHub",
    href: "https://github.com",
    owner: "GitHub",
    rule: "Text identification only; no provider logo.",
    source_url: "https://github.com",
    changed: null,
    files: {},
    plate: null,
    monogram: "GitHub",
  },
  dbt: {
    label: "dbt",
    href: "https://www.getdbt.com",
    owner: "dbt Labs, LLC",
    rule: "Text identification only. Logo use needs written permission. https://www.getdbt.com/dbt-assets/dbt-trademark-guidelines",
    source_url: "https://www.getdbt.com",
    changed: null,
    files: {},
    plate: null,
    monogram: "dbt",
  },
  mdp: {
    label: "Music Data Platform",
    href: "/",
    owner: "Music Data Platform",
    rule: "Music Data Platform app mark. Open /sources for data providers.",
    source_url: "README.md",
    changed: "Neutral MDP text mark generated for this snapshot",
    files: {
      onDark: "mdp.svg",
      onLight: "mdp.svg",
    },
    plate: "dark",
    monogram: null,
  },
  watch_list: {
    label: "Watch list",
    href: "/sources",
    owner: "Music Data Platform",
    rule: "App glyph. Open /sources to see the watch list.",
    source_url: "/sources",
    changed: null,
    files: {},
    plate: null,
    monogram: "☷",
  },
  access: {
    label: "Access",
    href: "/sources",
    owner: "Music Data Platform",
    rule: "App glyph. Open /sources to see the access method.",
    source_url: "/sources",
    changed: null,
    files: {},
    plate: null,
    monogram: "↗",
  },
};
