{# Generated by mdp sources export; function schemas own raw DDL. #}
{% macro bootstrap_raw() %}
  {% if target.name in ('dev', 'ci') and execute %}
    {% do run_query("create schema if not exists raw") %}
__DDL__
  {% endif %}
{% endmacro %}
