{# Generated by mdp sources export from tenant models' reads; regenerate, never edit. #}
{% macro mdp_global_inputs(cadence) %}
  {# Per cadence, the global raw tables tenant models read; dbt_job.global_inputs mirrors it. #}
  {% set declared = __DECLARED__ %}
  {{ return(declared.get(cadence, [])) }}
{% endmacro %}

{% macro mdp_global_tables() %}
  {# Raw tables that global functions write. #}
  {{ return(__GLOBAL__) }}
{% endmacro %}
