{# Generated by ops/ci/generate_health_policy.py. Do not edit. #}
{% macro mdp_scheduled_cycle(column) -%}
left({{ column }}, 7) <> 'manual:' AND left({{ column }}, 9) <> 'backfill:' AND left({{ column }}, 7) <> 'canary:'
{%- endmacro %}
