{# Generated by `mdp sources export` from mdp_functions/owners.py (rule 73c4def75279); do not edit. #}

{% macro mdp_owner_observed_class() -%}
{%- if target.type == 'postgres' -%}
coalesce(owner_class_observed, case
        when platform = 'spotify' and fetch_surface = 'sp_playlist_embed' and coalesce(cast(attributes as jsonb) @> '[{"key":"isAlgotorial","value":"true"}]'::jsonb, false) then 'dsp_algorithmic'
        when platform = 'spotify' and owner_id in ('spotify') then 'editorial'
        when platform = 'spotify' and owner_id is not null then 'user'
        when platform = 'apple_music' and playlist_id like 'pl.u-%' then 'user'
        when platform = 'apple_music' and owner_id like 'sp.%' then 'user'
        when platform = 'apple_music' and owner_name like 'Apple Music%' then 'editorial'
        when platform = 'apple_music' and playlist_id ~ '^pl\.[0-9a-f]{32}$' and owner_id ~ '^[0-9]+$' then 'editorial'
        when platform = 'apple_music' and playlist_id ~ '^pl\.[0-9a-f]{32}$' and owner_id is null and platform_version is not null then 'editorial'
        when platform = 'soundcloud' and playlist_id like 'soundcloud:%' then 'dsp_algorithmic'
        when platform = 'soundcloud' and owner_id = '193' then 'editorial'
        when fetch_surface = 'bc_discover' then 'chart'
        when fetch_surface = 'bc_daily_list' then 'editorial'
        when fetch_surface = 'bc_radio' then 'editorial'
        else 'unknown' end)
{%- else -%}
coalesce(owner_class_observed, case
        when platform = 'spotify' and fetch_surface = 'sp_playlist_embed' and coalesce(json_contains(attributes, '{"key":"isAlgotorial","value":"true"}'), false) then 'dsp_algorithmic'
        when platform = 'spotify' and owner_id in ('spotify') then 'editorial'
        when platform = 'spotify' and owner_id is not null then 'user'
        when platform = 'apple_music' and playlist_id like 'pl.u-%' then 'user'
        when platform = 'apple_music' and owner_id like 'sp.%' then 'user'
        when platform = 'apple_music' and owner_name like 'Apple Music%' then 'editorial'
        when platform = 'apple_music' and regexp_matches(playlist_id, '^pl\.[0-9a-f]{32}$') and regexp_matches(owner_id, '^[0-9]+$') then 'editorial'
        when platform = 'apple_music' and regexp_matches(playlist_id, '^pl\.[0-9a-f]{32}$') and owner_id is null and platform_version is not null then 'editorial'
        when platform = 'soundcloud' and playlist_id like 'soundcloud:%' then 'dsp_algorithmic'
        when platform = 'soundcloud' and owner_id = '193' then 'editorial'
        when fetch_surface = 'bc_discover' then 'chart'
        when fetch_surface = 'bc_daily_list' then 'editorial'
        when fetch_surface = 'bc_radio' then 'editorial'
        else 'unknown' end)
{%- endif -%}
{%- endmacro %}

{% macro mdp_owner_is_public(observed) -%}
{{ observed }} in ('editorial','chart','dsp_algorithmic')
{%- endmacro %}

{% macro mdp_owner_served_name(observed) -%}
case
    when fetch_surface = 'bc_daily_list' then 'Bandcamp Daily'
    when {{ observed }} in ('editorial','chart','dsp_algorithmic') then owner_name end
{%- endmacro %}

{% macro mdp_owner_served_class(observed) -%}
case when {{ observed }} = 'unknown' then coalesce(owner_class, 'unknown')
    when {{ observed }} = 'editorial' and owner_class = 'chart' then 'chart'
    else {{ observed }} end
{%- endmacro %}
