{# Generated by mdp sources export from tenant models' reads; regenerate, never edit. #}
{% macro mdp_global_inputs(cadence) %}
  {# Per cadence, the global raw tables tenant models read; dbt_job.global_inputs mirrors it. #}
  {% set declared = {"daily": [], "hourly": [], "weekly": []} %}
  {{ return(declared.get(cadence, [])) }}
{% endmacro %}

{% macro mdp_global_tables() %}
  {# Raw tables that global functions write. #}
  {{ return(["raw.apple_song_durations", "raw.bc_releases", "raw.bc_tracks", "raw.chart_entries", "raw.jev_instrument_family", "raw.lb_fresh_releases", "raw.lb_popularity", "raw.lb_similar_artists", "raw.lb_sitewide", "raw.mb_artist", "raw.mb_artist_catalog", "raw.mb_artist_credit", "raw.mb_artist_credit_name", "raw.mb_artist_ipi", "raw.mb_artist_isni", "raw.mb_artist_release_groups", "raw.mb_generation", "raw.mb_isrc", "raw.mb_l_artist_label", "raw.mb_l_label_label", "raw.mb_label", "raw.mb_medium", "raw.mb_recording", "raw.mb_redirect", "raw.mb_release", "raw.mb_release_group", "raw.mb_resolve", "raw.mb_resolve_closure", "raw.mb_track", "raw.mb_url_link", "raw.playlist_candidates", "raw.playlist_items", "raw.playlist_snapshots", "raw.radio_plays", "raw.sc_tracks", "raw.shazam_chart_entries", "raw.sp_track_artists", "raw.track_isrc_crosswalk", "raw.wiki_lookups", "raw.wiki_pageviews", "raw.wiki_sitelinks"]) }}
{% endmacro %}
