{# Generated by `mdp sources export` from mdp_functions/name_folding.py; do not edit. #}

{% macro mdp_fold_name(expression) -%}
trim(regexp_replace(translate({{ expression }}, chr(65) || chr(66) || chr(67) || chr(68) || chr(69) || chr(70) || chr(71) || chr(72) || chr(73) || chr(74) || chr(75) || chr(76) || chr(77) || chr(78) || chr(79) || chr(80) || chr(81) || chr(82) || chr(83) || chr(84) || chr(85) || chr(86) || chr(87) || chr(88) || chr(89) || chr(90) || chr(32) || chr(9) || chr(10) || chr(13) || chr(11) || chr(12) || chr(28) || chr(29) || chr(30) || chr(31) || chr(133) || chr(160) || chr(5760) || chr(8192) || chr(8193) || chr(8194) || chr(8195) || chr(8196) || chr(8197) || chr(8198) || chr(8199) || chr(8200) || chr(8201) || chr(8202) || chr(8232) || chr(8233) || chr(8239) || chr(8287) || chr(12288), 'abcdefghijklmnopqrstuvwxyz                             '), ' +', ' ', 'g'))
{%- endmacro %}
