{# Generated by mdp sources export from function Targets and model meta.target_kinds; regenerate, never edit. #}
{% macro mdp_export_kinds(cadence, scope) %}
  {# Per cadence and scope, the target kinds the export freezes. In a tenant export a bare kind
     freezes the tenant's sets and `global:<kind>` the global sets its tenant functions read. #}
  {% set declared = {"daily:global": ["artist_page", "chart", "curator", "playlist", "track"], "daily:tenant": [], "hourly:global": [], "hourly:tenant": [], "weekly:global": [], "weekly:tenant": []} %}
  {{ return(declared.get(cadence ~ ':' ~ scope, [])) }}
{% endmacro %}
