"""Generate the error hints shared by the console, Python and R."""

import argparse
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[4]
CATALOG = ROOT / "docs/errors/catalog.yml"


def read_catalog():
    rows = yaml.safe_load(CATALOG.read_text())
    if not isinstance(rows, dict) or "unmapped" not in rows:
        raise ValueError("Add the unmapped fallback to docs/errors/catalog.yml")
    books = {p.stem.replace("_", "-") for p in (ROOT / "ops/runbooks").glob("*.md")}
    for code, row in rows.items():
        if not isinstance(row, dict) or set(row) != {"summary", "next_step", "runbook"}:
            raise ValueError(f"{code}: supply summary, next_step and runbook (or null)")
        for field in ("summary", "next_step"):
            if not isinstance(row[field], str) or not row[field].strip():
                raise ValueError(f"{code}: add a nonempty {field}")
        if row["runbook"] is not None and row["runbook"] not in books:
            raise ValueError(
                f"{code}: runbook {row['runbook']} does not exist; choose an ops/runbooks file"
            )
    return dict(sorted(rows.items()))


def outputs(rows):
    data = json.dumps(rows, indent=2, ensure_ascii=False) + "\n"
    return {
        ROOT / "control/packages/contracts/src/error-catalog.ts": (
            "// Generated by scripts/error-catalog.py; edit docs/errors/catalog.yml.\n"
            "export type ErrorHint = { summary: string; next_step: string; runbook: string | null };\n"
            "export const errorCatalog = "
            + data.rstrip()
            + " as const satisfies Record<string, ErrorHint>;\n"
            "export type ErrorClass = keyof typeof errorCatalog;\n"
            "export function errorHint(code: string): ErrorHint {\n"
            "  return Object.hasOwn(errorCatalog, code) ? errorCatalog[code as ErrorClass] : errorCatalog.unmapped;\n"
            "}\n"
        ),
        ROOT / "functions/src/mdp_functions/error_catalog.json": data,
        ROOT / "r/mdpr/inst/extdata/error_catalog.json": data,
    }


def generate(check=False):
    stale = []
    for path, content in outputs(read_catalog()).items():
        if check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise ValueError(
            "Stale: "
            + ", ".join(stale)
            + "; run pnpm --dir control --filter @mdp/contracts error-catalog"
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    generate(parser.parse_args().check)
