#!/usr/bin/env python3
"""Write the showcase's dot-matrix world from Natural Earth's public-domain 110m land outline.

Run from the repository root: python3 ops/showcase/world-land.py
It fetches one pinned file and writes control/apps/showcase/lib/world-land.ts. Never edit that file.
"""

import json
import urllib.request
from pathlib import Path

SOURCE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/v5.1.2/geojson/ne_110m_land.geojson"
OUT = Path(__file__).resolve().parents[2] / "control/apps/showcase/lib/world-land.ts"
STEP = 3  # degrees per cell
NORTH, SOUTH = 84, -60  # Antarctica stays off the map


def inside(lon, lat, ring):
    hit = False
    for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1]):
        if (y1 > lat) != (y2 > lat) and lon < (x2 - x1) * (lat - y1) / (y2 - y1) + x1:
            hit = not hit
    return hit


def main():
    with urllib.request.urlopen(SOURCE, timeout=30) as response:
        features = json.load(response)["features"]
    polygons = []
    for feature in features:
        geometry = feature["geometry"]
        shapes = (
            [geometry["coordinates"]]
            if geometry["type"] == "Polygon"
            else geometry["coordinates"]
        )
        polygons += [
            [[tuple(point) for point in ring] for ring in shape] for shape in shapes
        ]
    cols, rows = 360 // STEP, (NORTH - SOUTH) // STEP
    lines = []
    for row in range(rows):
        lat = NORTH - (row + 0.5) * STEP
        bits = ""
        for col in range(cols):
            lon = -180 + (col + 0.5) * STEP
            land = any(
                inside(lon, lat, shape[0])
                and not any(inside(lon, lat, hole) for hole in shape[1:])
                for shape in polygons
            )
            bits += "1" if land else "0"
        lines.append(f"{int(bits, 2):0{cols // 4}x}")
    body = ",\n".join(f'  "{line}"' for line in lines)
    OUT.write_text(
        "// Generated by ops/showcase/world-land.py from Natural Earth 110m land (public domain). Do not edit.\n"
        f"// Each string is one {STEP}-degree band from {NORTH} N to {abs(SOUTH)} S; each hex digit holds four cells from 180 W.\n"
        f"export const landStep = {STEP};\nexport const landNorth = {NORTH};\nexport const landColumns = {cols};\n"
        f"export const landRows = [\n{body},\n];\n"
    )
    print(
        f"Wrote {OUT.relative_to(Path.cwd()) if OUT.is_relative_to(Path.cwd()) else OUT}: {rows} bands of {cols} cells."
    )


if __name__ == "__main__":
    main()
