import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync, rmSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "../../../..");
const name = z.string().regex(/^[a-z][a-z0-9_]*$/);
export function scaffold(mart: string) {
  name.parse(mart);
  if (
    !existsSync(
      resolve(root, `control/packages/data-sdk/src/generated/${mart}.zod.ts`),
    )
  )
    throw new Error("Generate the SDK from the mart contract first");
  const dir = resolve(root, "control/apps/data-api/src/generated");
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    resolve(dir, `${mart}.ts`),
    `// Generated by pnpm mdp scaffold api ${mart}.\nimport { implement } from '@orpc/server';\nimport { dataContract,${mart},metadata_${mart},encode_${mart} } from '@mdp/data-sdk';\nimport { readMart,type ReadContext } from '../read.js';\nexport const procedure=implement(dataContract.${mart}).$context<ReadContext>().handler(({context,input})=>readMart(context,metadata_${mart},${mart},encode_${mart},input));\n`,
  );
  // Retire generated routes whose contracts were removed.
  for (const file of readdirSync(dir)) {
    if (file.endsWith('.ts') && file !== 'router.ts' && !existsSync(resolve(root, `control/packages/data-sdk/src/generated/${file.slice(0, -3)}.zod.ts`))) rmSync(resolve(dir, file));
  }
  const marts = readdirSync(dir)
    .filter((n) => n.endsWith(".ts") && n !== "router.ts")
    .map((n) => name.parse(n.slice(0, -3)))
    .sort();
  writeFileSync(
    resolve(dir, "router.ts"),
    "// Generated procedure registry.\n" +
      marts
        .map((m) => `import { procedure as ${m} } from './${m}.js';`)
        .join("\n") +
      `\nexport const router={${marts.join(",")}};\n`,
  );
  writeFileSync(
    resolve(root, "control/packages/data-sdk/src/data-contract.ts"),
    `// Generated by pnpm mdp scaffold api.\nimport { martProcedure } from './mart-procedure.js';\nimport { ${marts.flatMap((m) => [m, `range_${m}`]).join(",")} } from './generated/marts.zod.js';\nexport const dataContract={${marts.map((m) => `${m}:martProcedure('${m}',${m},range_${m})`).join(",")}};\n`,
  );
  writeFileSync(
    resolve(root, "control/packages/data-sdk/src/client.ts"),
    `// Generated by pnpm mdp scaffold api.
import { createORPCClient } from '@orpc/client';
import { RPCLink } from '@orpc/client/fetch';
import type { ContractRouterClient } from '@orpc/contract';
import { z } from 'zod';
import { dataContract } from './data-contract.js';
function decodeOutput<T extends z.ZodType>(schema:T|undefined,value:unknown):z.output<T> {if(!schema)throw new Error('Missing output contract');return schema.parse(value);}
export function createDataClient(url:string,headers:Record<string,string>={}) {
 const client:ContractRouterClient<typeof dataContract>=createORPCClient(new RPCLink({url:new URL('/rpc',url).toString(),headers}));
 return {${marts.map((m) => `${m}:async(input:Parameters<typeof client.${m}>[0])=>decodeOutput(dataContract.${m}['~orpc'].outputSchema,await client.${m}(input))`).join(",")}};
}
`,
  );
  console.log(
    `Scaffolded ${mart}: contract filters, time ranges, grain cursor paging, session tenant injection`,
  );
}
