[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/run/supervisord.pid

[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:postgres]
command=/opt/mdp/boot/postgres.sh
priority=20
autorestart=true
startsecs=2
startretries=20
stopsignal=INT
stopwaitsecs=60
stdout_logfile=/dev/null
stdout_logfile_maxbytes=0
stderr_logfile=/dev/null
stderr_logfile_maxbytes=0

[include]
files=/run/mdp/pgduck-supervisor.conf

[program:query-audit]
command=python3 /opt/mdp/boot/query-audit.py
user=postgres
priority=30
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:sandbox-check]
command=python3 /opt/mdp/boot/sandbox-check.py
user=postgres
priority=30
autorestart=true
startsecs=2
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
