-- Warehouse only. Control privileges remain owned by Drizzle.
BEGIN;
-- Library search uses an indexed trigram comparison. Bootstrap also runs this on existing volumes.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
-- PostgreSQL 17 closes overdue read sessions and releases their locks.
ALTER ROLE reader_wh SET transaction_timeout = '6s';
ALTER ROLE reader_wh SET statement_timeout = '5s';
-- Human logins inherit only this group; no service credentials are shared.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'analyst_ro') THEN
    CREATE ROLE analyst_ro NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='explorer_ro') THEN
    CREATE ROLE explorer_ro NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
  END IF;
END $$;
GRANT CONNECT ON DATABASE warehouse TO analyst_ro, explorer_ro;
-- Fresh installs can inherit PUBLIC execute; upgrades inherit the hardened defaults below.
-- Reconcile both paths, then allow only the two functions used by Library reads.
DO $$ DECLARE f regprocedure; BEGIN
  FOR f IN SELECT p.oid::regprocedure FROM pg_proc p
    JOIN pg_depend d ON d.classid='pg_proc'::regclass AND d.objid=p.oid AND d.deptype='e'
    JOIN pg_extension e ON e.oid=d.refobjid AND e.extname='pg_trgm'
  LOOP
    EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM PUBLIC', f);
  END LOOP;
END $$;
GRANT EXECUTE ON FUNCTION public.similarity(text,text), public.similarity_op(text,text)
  TO showcase_wh, analyst_ro, reader_wh;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS raw AUTHORIZATION loader_wh;
ALTER SCHEMA raw OWNER TO loader_wh;
GRANT USAGE ON SCHEMA raw TO dbt_transform, service_read, reader_wh;
REVOKE ALL ON SCHEMA raw FROM workbench_wh;
REVOKE ALL ON ALL TABLES IN SCHEMA raw FROM workbench_wh;
GRANT SELECT ON ALL TABLES IN SCHEMA raw TO dbt_transform, service_read;
ALTER DEFAULT PRIVILEGES FOR ROLE loader_wh IN SCHEMA raw
  GRANT SELECT ON TABLES TO dbt_transform, service_read;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA raw
  GRANT SELECT ON TABLES TO dbt_transform, service_read;
GRANT CREATE ON DATABASE warehouse TO dbt_transform, workbench_wh;
-- dbt's delete+insert incremental strategy stages each batch in a temporary table.
GRANT TEMPORARY ON DATABASE warehouse TO dbt_transform;
-- pg_lake DELETE/repair stages affected rows in a transaction-local temp table.
DO $$ DECLARE relation text; BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname='pg_lake') THEN
    GRANT TEMPORARY ON DATABASE warehouse TO loader_wh;
    -- Extension metadata is for warehouse services, not human logins. Preserve the
    -- services' existing reads before removing the extension's PUBLIC grants.
    FOREACH relation IN ARRAY ARRAY[
      'lake_iceberg.tables', 'lake_iceberg.tables_external', 'lake_iceberg.tables_internal',
      'lake_table.row_id_mappings', '__pg_lake_table_writes.row_id_mappings'
    ] LOOP
      IF to_regclass(relation) IS NOT NULL THEN
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO dbt_transform,loader_wh,service_read',split_part(relation,'.',1));
        EXECUTE format('GRANT SELECT ON %s TO dbt_transform,loader_wh,service_read',relation);
        EXECUTE format('REVOKE SELECT ON %s FROM PUBLIC',relation);
      END IF;
    END LOOP;
  END IF;
END $$;
CREATE SCHEMA IF NOT EXISTS mdp;
-- sandbox-policy:start
-- Generated by ops/ci/generate_sandbox_policy.py.
CREATE OR REPLACE FUNCTION mdp.sandbox_policy() RETURNS jsonb
LANGUAGE sql IMMUTABLE SET search_path=pg_catalog AS $policy$ SELECT $json${"prefix": "sandbox_", "handle_pattern": "^[a-z][a-z0-9_]{0,47}$", "object_pattern": "^[a-z][a-z0-9_]{0,62}$", "connection_limit": 4, "statement_timeout": "30s", "idle_in_transaction_session_timeout": "60s", "temp_file_limit": "256MB", "quota_bytes": 1073741824, "warn_fraction": 0.8, "poll_seconds": 60, "archive_root": "inputs/sandbox-archives", "runtime_roles": ["reader_wh", "showcase_wh", "api_key_reader", "dbt_transform", "loader_wh", "service_read", "functions_rt", "control_rt", "workbench_wh"], "messages": {"sandbox_account_refused": "This login is not a standard individual analyst or explorer account. Inspect its memberships with psql \\du <login>; use a separate individual login.", "sandbox_acl_alert": "Sandbox grants exceed the allowed sharing scope. Freeze the login and inspect its grants with the operator sandbox status command.", "sandbox_acl_refused": "Sandbox access cannot be delegated or granted to runtime roles. Share SELECT with the allowed human group without WITH GRANT OPTION.", "sandbox_archive_blocked": "Other objects depend on this sandbox. Notify the listed owners and remove or transfer their dependencies, then run archive again.", "sandbox_archive_failed": "Archive failed; the login stays disabled and data is kept. Inspect the archive manifest and rerun archive with a new destination.", "sandbox_frozen": "New objects are blocked while the sandbox is frozen. Delete unused tables, run mdp warehouse sandbox status, and ask the operator to unfreeze a manual hold.", "sandbox_handle_invalid": "A handle uses 1–48 lowercase letters, digits or underscores, starts with a letter, and is not ro. Choose a handle such as demo.", "sandbox_missing": "This login has no owned sandbox. Ask an operator to run ops/fly/postgres/analyst-add.sh <handle>, then reconnect.", "sandbox_object_invalid": "The object name must use lowercase SQL letters, digits and underscores. Choose a name such as chart_draft.", "sandbox_owner_conflict": "This sandbox belongs to another login. Choose another handle, or ask an operator to inspect it with mdp warehouse sandbox status and archive the stale schema before reuse.", "sandbox_quota_warning": "Sandbox storage is at least 80 percent full. Run mdp warehouse sandbox status and remove unused tables before creating more.", "sandbox_snapshot_failed": "The snapshot was not published. Check MDP_ANALYST_URL (in R, reconnect with mdp_connect()), choose a readable schema, and rerun with a new output path.", "sandbox_stamp_denied": "Build stamps need a readable relation. Choose a readable entry in catalog.relations and rerun the snapshot.", "sandbox_status_failed": "Sandbox status is unavailable. Reconnect with MDP_ANALYST_URL or ask an operator to run mdp warehouse sandbox status --all.", "sandbox_view_refused": "A persistent sandbox view or SQL routine can block production schema changes. Save a table with CREATE TABLE sandbox_<handle>.<name> AS SELECT instead, or lift a view over a served mart.", "sandbox_write_failed": "The sandbox write failed. Choose a new name or use overwrite = TRUE in mdp_write() for your own table; for a view, check its columns and save from a served mart.", "workbench_permission_denied": "The workbench role cannot read this relation. Use the safe copy when offered and rerun. Otherwise open Explorer and choose a permitted global input, or ask an operator to restore analyst access.", "workbench_query_failed": "The warehouse could not run this query. Check the relation and column names in the catalog, then rerun.", "workbench_statement_timeout": "This query exceeded the statement timeout. Filter earlier or read fewer rows, then rerun; use a local snapshot for longer analysis."}}$json$::jsonb $policy$;
REVOKE ALL ON FUNCTION mdp.sandbox_policy() FROM PUBLIC,service_read;
CREATE OR REPLACE FUNCTION mdp.is_sandbox(schema_name text) RETURNS boolean LANGUAGE sql IMMUTABLE SET search_path=pg_catalog AS $predicate$ SELECT starts_with(schema_name, mdp.sandbox_policy()->>'prefix') $predicate$;
REVOKE ALL ON FUNCTION mdp.is_sandbox(text) FROM PUBLIC,service_read;
-- sandbox-policy:end
REVOKE ALL ON SCHEMA mdp FROM PUBLIC;
GRANT USAGE ON SCHEMA mdp TO dbt_transform, service_read;
-- The staging pseudonym key (mdp_pseudonym), generated once; only dbt_transform reads it.
CREATE TABLE IF NOT EXISTS mdp.pseudonym_key(id boolean PRIMARY KEY DEFAULT true CHECK (id), key text NOT NULL);
INSERT INTO mdp.pseudonym_key(key) VALUES (gen_random_uuid()::text || gen_random_uuid()::text) ON CONFLICT DO NOTHING;
REVOKE ALL ON mdp.pseudonym_key FROM PUBLIC, service_read, workbench_wh, reader_wh, loader_wh;
GRANT SELECT ON mdp.pseudonym_key TO dbt_transform;
-- PUBLIC's global default cannot be removed by a schema-scoped revoke.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE dbt_transform REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO service_read;
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO service_read;
ALTER DEFAULT PRIVILEGES FOR ROLE loader_wh GRANT SELECT ON TABLES TO service_read;
ALTER DEFAULT PRIVILEGES FOR ROLE dbt_transform GRANT SELECT ON TABLES TO service_read;
ALTER DEFAULT PRIVILEGES FOR ROLE workbench_wh GRANT SELECT ON TABLES TO service_read;
ALTER DEFAULT PRIVILEGES FOR ROLE dbt_transform REVOKE SELECT ON TABLES FROM workbench_wh;
ALTER DEFAULT PRIVILEGES FOR ROLE loader_wh IN SCHEMA raw REVOKE SELECT ON TABLES FROM workbench_wh;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA raw REVOKE SELECT ON TABLES FROM workbench_wh;
ALTER DEFAULT PRIVILEGES FOR ROLE dbt_transform GRANT USAGE ON SCHEMAS TO service_read;
ALTER DEFAULT PRIVILEGES FOR ROLE loader_wh GRANT USAGE ON SCHEMAS TO service_read;
ALTER DEFAULT PRIVILEGES FOR ROLE workbench_wh GRANT USAGE ON SCHEMAS TO service_read;

-- Defaults precede schemas; explicit grants also repair an existing volume.
CREATE SCHEMA IF NOT EXISTS staging AUTHORIZATION dbt_transform;
CREATE SCHEMA IF NOT EXISTS intermediate AUTHORIZATION dbt_transform;
CREATE SCHEMA IF NOT EXISTS marts AUTHORIZATION dbt_transform;
GRANT USAGE ON SCHEMA staging, intermediate, marts TO analyst_ro, service_read, workbench_wh;
GRANT SELECT ON ALL TABLES IN SCHEMA staging, intermediate, marts TO service_read;
-- Staff table access comes from the generated column policy below, including on repaired volumes.
REVOKE SELECT ON ALL TABLES IN SCHEMA staging, intermediate, marts FROM analyst_ro, explorer_ro, workbench_wh;
ALTER DEFAULT PRIVILEGES FOR ROLE dbt_transform IN SCHEMA staging, intermediate, marts
  GRANT SELECT ON TABLES TO service_read;
ALTER DEFAULT PRIVILEGES FOR ROLE dbt_transform IN SCHEMA staging, intermediate, marts
  REVOKE SELECT ON TABLES FROM analyst_ro, explorer_ro, workbench_wh;

CREATE OR REPLACE FUNCTION mdp.protect_function_execute() RETURNS event_trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog AS $$
DECLARE f record; human_group text;
BEGIN
  FOR f IN SELECT p.oid::regprocedure AS signature FROM pg_event_trigger_ddl_commands() c
    JOIN pg_proc p ON c.classid = 'pg_proc'::regclass AND c.objid = p.oid
    JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'mdp' OR mdp.is_sandbox(n.nspname)
  LOOP
    EXECUTE format('REVOKE EXECUTE ON ROUTINE %s FROM PUBLIC, service_read', f.signature);
    FOR human_group IN SELECT rolname FROM pg_roles WHERE rolname IN ('analyst_ro','explorer_ro') LOOP
      EXECUTE format('REVOKE EXECUTE ON ROUTINE %s FROM %I',f.signature,human_group);
    END LOOP;
  END LOOP;
END $$;
REVOKE ALL ON FUNCTION mdp.protect_function_execute() FROM PUBLIC, service_read;

-- ddl_command_start has no parsed object list. Fail closed for workbench SQL:
-- accept a single, plain CREATE SCHEMA [IF NOT EXISTS] wb_* statement only.
-- The catalog-based end guard also protects dynamic SQL and schema renames.
CREATE OR REPLACE FUNCTION mdp.guard_workbench_schema_start() RETURNS event_trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog AS $$
BEGIN
  IF current_user = 'workbench_wh' AND current_query() !~*
    '^\s*CREATE\s+SCHEMA\s+(IF\s+NOT\s+EXISTS\s+)?(wb_[a-z0-9_]+|"wb_[a-z0-9_]+")\s*(AUTHORIZATION\s+workbench_wh\s*)?;?\s*$'
  THEN
    RAISE EXCEPTION 'workbench schema must use wb_*; submit a single CREATE SCHEMA statement' USING ERRCODE = '42501';
  END IF;
END $$;
REVOKE ALL ON FUNCTION mdp.guard_workbench_schema_start() FROM PUBLIC, service_read;

CREATE OR REPLACE FUNCTION mdp.guard_workbench_schema_end() RETURNS event_trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_event_trigger_ddl_commands() c
    JOIN pg_namespace n ON c.classid = 'pg_namespace'::regclass AND c.objid = n.oid
    WHERE (current_user = 'workbench_wh' OR n.nspowner = 'workbench_wh'::regrole)
      AND n.nspname !~ '^wb_') THEN
    RAISE EXCEPTION 'workbench schema must use wb_*' USING ERRCODE = '42501';
  END IF;
END $$;
REVOKE ALL ON FUNCTION mdp.guard_workbench_schema_end() FROM PUBLIC, service_read;

-- Shared by the event trigger and the existing-table reconciliation below.
CREATE OR REPLACE FUNCTION mdp.grant_warehouse_table(rel oid) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog AS $$
DECLARE s text; t text; cols text; human_group text;
BEGIN
  SELECT n.nspname, c.relname INTO s,t FROM pg_class c
    JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE c.oid=rel AND c.relkind IN ('r','p','f','v','m');
  IF s IS NULL OR s LIKE 'pg\_%' OR s IN ('information_schema','control','mdp','catalog') THEN RETURN; END IF;
  IF mdp.is_sandbox(s) THEN
    -- Only the original owner's sharing class applies, including while frozen.
    FOR human_group IN SELECT r.rolname FROM pg_roles r
      WHERE r.rolname='explorer_ro' OR (r.rolname='analyst_ro' AND NOT EXISTS (
        SELECT 1 FROM mdp.sandbox_state st WHERE st.schema_name=s AND st.is_explorer)) LOOP
      IF NOT has_schema_privilege(human_group,s,'USAGE') THEN
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO %I',s,human_group);
      END IF;
      EXECUTE format('GRANT SELECT ON TABLE %I.%I TO %I',s,t,human_group);
    END LOOP;
    RETURN;
  END IF;
  EXECUTE format('GRANT SELECT ON TABLE %I.%I TO service_read',s,t);
  -- Staff access is reconciled from the generated column policy, never from a schema name.
  IF to_regprocedure('catalog.share_relation(oid)') IS NOT NULL THEN
    PERFORM catalog.share_relation(rel);
  ELSIF s NOT LIKE 'wb\_%' THEN
    EXECUTE format('REVOKE SELECT ON TABLE %I.%I FROM analyst_ro,explorer_ro,workbench_wh',s,t);
  END IF;
  IF s='raw' THEN
    EXECUTE format('GRANT SELECT ON TABLE %I.%I TO dbt_transform',s,t);
    -- Column ACLs survive renames. Reconcile them so a former lineage column
    -- cannot become readable payload after ALTER TABLE RENAME COLUMN.
    EXECUTE format('REVOKE SELECT ON TABLE %I.%I FROM reader_wh',s,t);
    SELECT string_agg(quote_ident(attname), ', ' ORDER BY attnum) INTO cols FROM pg_attribute
      WHERE attrelid=rel AND attnum>0 AND NOT attisdropped;
    IF cols IS NOT NULL THEN
      EXECUTE format('REVOKE SELECT (%s) ON TABLE %I.%I FROM reader_wh',cols,s,t);
    END IF;
    SELECT string_agg(quote_ident(attname), ', ' ORDER BY attnum) INTO cols FROM pg_attribute
      WHERE attrelid=rel AND attnum>0 AND NOT attisdropped AND attname = ANY(ARRAY[
        '_run_id','_dump_id','_landed_seq','_cycle_id','_revision_id','_target_id',
        '_request_id','_source_key','_ingested_at']);
    IF cols IS NOT NULL THEN
      EXECUTE format('GRANT SELECT (%s) ON TABLE %I.%I TO reader_wh',cols,s,t);
    END IF;
  ELSIF s='marts' OR s LIKE 'tenant\_%\_marts' THEN
    -- reader_wh reads marts and tenant marts only, never tenant staging or intermediate.
    -- Avoid rewriting a shared schema ACL during parallel table creation.
    IF NOT has_schema_privilege('reader_wh',s,'USAGE') THEN
      EXECUTE format('GRANT USAGE ON SCHEMA %I TO reader_wh',s);
    END IF;
    EXECUTE format('GRANT SELECT ON TABLE %I.%I TO reader_wh',s,t);
  END IF;
END $$;
REVOKE ALL ON FUNCTION mdp.grant_warehouse_table(oid) FROM PUBLIC, service_read;

CREATE OR REPLACE FUNCTION mdp.refresh_warehouse_grants() RETURNS event_trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog AS $$
DECLARE c record; s text;
BEGIN
  -- Operate only on affected objects to avoid racing concurrent dbt schemas.
  FOR c IN SELECT * FROM pg_event_trigger_ddl_commands() LOOP
    IF c.classid='pg_namespace'::regclass THEN
      SELECT nspname INTO s FROM pg_namespace WHERE oid=c.objid;
      IF s NOT LIKE 'pg\_%' AND NOT mdp.is_sandbox(s) AND s NOT IN ('information_schema','control','mdp') THEN
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO service_read',s);
        IF s NOT IN ('raw','catalog') AND s NOT LIKE 'wb\_%' THEN
          EXECUTE format('GRANT USAGE ON SCHEMA %I TO explorer_ro',s);
        END IF;
        IF s='marts' OR s LIKE 'tenant\_%\_marts' THEN
          EXECUTE format('GRANT USAGE ON SCHEMA %I TO reader_wh',s);
        END IF;
      END IF;
    ELSIF c.classid='pg_class'::regclass THEN
      PERFORM mdp.grant_warehouse_table(c.objid);
    END IF;
  END LOOP;
END $$;
REVOKE ALL ON FUNCTION mdp.refresh_warehouse_grants() FROM PUBLIC, service_read;

-- DROP/CREATE is atomic within this transaction and repairs old trigger tags.
DROP EVENT TRIGGER IF EXISTS mdp_warehouse_grants;
CREATE EVENT TRIGGER mdp_warehouse_grants ON ddl_command_end
  WHEN TAG IN ('CREATE SCHEMA','CREATE TABLE','CREATE TABLE AS','SELECT INTO',
               'ALTER TABLE','CREATE FOREIGN TABLE','ALTER FOREIGN TABLE','CREATE VIEW','CREATE MATERIALIZED VIEW')
  EXECUTE FUNCTION mdp.refresh_warehouse_grants();
DROP EVENT TRIGGER IF EXISTS mdp_function_execute;
CREATE EVENT TRIGGER mdp_function_execute ON ddl_command_end
  WHEN TAG IN ('CREATE FUNCTION','CREATE PROCEDURE') EXECUTE FUNCTION mdp.protect_function_execute();
DROP EVENT TRIGGER IF EXISTS mdp_workbench_schema_start;
CREATE EVENT TRIGGER mdp_workbench_schema_start ON ddl_command_start
  WHEN TAG IN ('CREATE SCHEMA') EXECUTE FUNCTION mdp.guard_workbench_schema_start();
DROP EVENT TRIGGER IF EXISTS mdp_workbench_schema_end;
CREATE EVENT TRIGGER mdp_workbench_schema_end ON ddl_command_end
  WHEN TAG IN ('CREATE SCHEMA','ALTER SCHEMA') EXECUTE FUNCTION mdp.guard_workbench_schema_end();

-- Scratch metadata has one writer: the warehouse operator. It is not cycle state.
CREATE TABLE IF NOT EXISTS mdp.sandbox_state (
  schema_name text PRIMARY KEY, owner_role name NOT NULL, is_explorer boolean NOT NULL,
  quota_bytes bigint NOT NULL, manual_frozen boolean NOT NULL DEFAULT false,
  quota_frozen boolean NOT NULL DEFAULT false, last_use timestamptz, last_calls bigint NOT NULL DEFAULT 0,
  archive_path text, updated_at timestamptz NOT NULL DEFAULT now()
);
REVOKE ALL ON mdp.sandbox_state FROM PUBLIC,analyst_ro,explorer_ro,service_read,workbench_wh,reader_wh,api_key_reader,dbt_transform,loader_wh,functions_rt,control_rt;
CREATE TABLE IF NOT EXISTS mdp.sandbox_notice (
  schema_name text NOT NULL, code text NOT NULL, message text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(schema_name,code)
);
REVOKE ALL ON mdp.sandbox_notice FROM PUBLIC,analyst_ro,explorer_ro,service_read,workbench_wh,reader_wh,api_key_reader,dbt_transform,loader_wh,functions_rt,control_rt;

CREATE SCHEMA IF NOT EXISTS catalog;
GRANT USAGE ON SCHEMA catalog TO analyst_ro,explorer_ro;
CREATE OR REPLACE VIEW catalog.sandbox_status WITH (security_barrier=true) AS
SELECT st.*,r.rolcanlogin AS login_enabled,
  coalesce((SELECT sum(pg_total_relation_size(c.oid)) FROM pg_class c WHERE c.relnamespace=n.oid AND c.relkind IN ('r','p','m')),0)::bigint AS size_bytes,
  (SELECT count(*)::int FROM pg_class c WHERE c.relnamespace=n.oid AND c.relkind IN ('r','p','v','m','f')) AS object_count,
  CASE WHEN st.is_explorer THEN 'explorers' ELSE 'analysts and explorers' END AS sharing
FROM mdp.sandbox_state st JOIN pg_namespace n ON n.nspname=st.schema_name JOIN pg_roles r ON r.rolname=st.owner_role
WHERE current_user=st.owner_role OR (SELECT rolsuper FROM pg_roles WHERE rolname=current_user)
 OR pg_has_role(current_user,'explorer_ro','MEMBER')
 OR (NOT st.is_explorer AND pg_has_role(current_user,'analyst_ro','MEMBER'));
REVOKE ALL ON catalog.sandbox_status FROM PUBLIC,service_read,workbench_wh;
GRANT SELECT ON catalog.sandbox_status TO analyst_ro,explorer_ro;
CREATE OR REPLACE VIEW catalog.sandbox_notices WITH (security_barrier=true) AS
SELECT n.* FROM mdp.sandbox_notice n JOIN catalog.sandbox_status s USING(schema_name);
REVOKE ALL ON catalog.sandbox_notices FROM PUBLIC,service_read,workbench_wh;
GRANT SELECT ON catalog.sandbox_notices TO analyst_ro,explorer_ro;

-- Expose a build stamp only for a relation this login can already read.
CREATE OR REPLACE FUNCTION catalog.snapshot_stamp(target text) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE caller name := coalesce(nullif(current_setting('role'),'none'),session_user);
  rel oid := to_regclass(target); namespace oid; schema_name text; canonical text; stamp jsonb;
BEGIN
  SELECT c.relnamespace,n.nspname, n.nspname||'.'||c.relname INTO namespace,schema_name,canonical
    FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.oid=rel;
  IF rel IS NULL OR NOT has_schema_privilege(caller,namespace,'USAGE') OR NOT has_table_privilege(caller,rel,'SELECT') THEN
    RAISE EXCEPTION '%',mdp.sandbox_policy()->'messages'->>'sandbox_stamp_denied' USING ERRCODE='42501';
  END IF;
  IF schema_name LIKE 'explore\_%' THEN
    SELECT n.nspname||'.'||c.relname INTO canonical
    FROM pg_rewrite rw JOIN pg_depend d ON d.classid='pg_rewrite'::regclass AND d.objid=rw.oid
      JOIN pg_class c ON c.oid=d.refobjid JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE rw.ev_class=rel AND d.refclassid='pg_class'::regclass AND c.oid<>rel AND n.nspname NOT IN ('mdp','catalog') LIMIT 1;
  END IF;
  IF to_regclass('marts._build') IS NULL THEN RETURN NULL; END IF;
  EXECUTE 'SELECT jsonb_build_object(''relation'',relation,''cycle_id'',cycle_id,''close_no'',close_no,''built_at'',built_at) FROM marts._build WHERE relation=$1' INTO stamp USING canonical;
  RETURN stamp;
END $$;
REVOKE ALL ON FUNCTION catalog.snapshot_stamp(text) FROM PUBLIC,service_read;
GRANT EXECUTE ON FUNCTION catalog.snapshot_stamp(text) TO analyst_ro,explorer_ro;

-- The same inspection runs after DDL and in the periodic operator check. Scan all
-- owners so SET ROLE or an old grant option cannot hide a delegated grant.
CREATE OR REPLACE FUNCTION mdp.sandbox_violations() RETURNS TABLE(schema_name text, code text)
LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $$
WITH spaces AS (
  SELECT n.*, coalesce(st.owner_role,pg_get_userbyid(n.nspowner)) AS owner_role,
    coalesce(st.is_explorer,pg_get_userbyid(n.nspowner) LIKE 'explorer\_%') AS is_explorer
  FROM pg_namespace n LEFT JOIN mdp.sandbox_state st ON st.schema_name=n.nspname
  WHERE mdp.is_sandbox(n.nspname)
), privileges AS (
  SELECT s.nspname,s.owner_role,s.is_explorer,a.*, 'USAGE' AS allowed FROM spaces s, aclexplode(s.nspacl) a
  UNION ALL
  SELECT s.nspname,s.owner_role,s.is_explorer,a.*, 'SELECT' FROM spaces s JOIN pg_class c ON c.relnamespace=s.oid, aclexplode(c.relacl) a
  UNION ALL
  SELECT s.nspname,s.owner_role,s.is_explorer,a.*, 'SELECT' FROM spaces s JOIN pg_class c ON c.relnamespace=s.oid JOIN pg_attribute col ON col.attrelid=c.oid, aclexplode(col.attacl) a
  UNION ALL
  SELECT s.nspname,s.owner_role,s.is_explorer,a.*, '' FROM spaces s JOIN pg_proc p ON p.pronamespace=s.oid, aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a
  UNION ALL
  SELECT s.nspname,s.owner_role,s.is_explorer,a.*, '' FROM spaces s JOIN pg_type t ON t.typnamespace=s.oid AND t.typrelid=0, aclexplode(t.typacl) a
  UNION ALL
  SELECT s.nspname,s.owner_role,s.is_explorer,a.*, CASE d.defaclobjtype WHEN 'r' THEN 'SELECT' ELSE '' END
  FROM spaces s JOIN pg_default_acl d ON d.defaclrole=to_regrole(s.owner_role) AND d.defaclnamespace IN (0,s.oid), aclexplode(d.defaclacl) a
)
SELECT DISTINCT p.nspname::text,'sandbox_acl_refused'::text FROM privileges p
WHERE p.grantee<>to_regrole(p.owner_role) AND p.grantee<>to_regrole('postgres')
  AND (p.is_grantable OR p.grantee=0 OR p.privilege_type<>p.allowed
       OR pg_get_userbyid(p.grantee) NOT IN ('analyst_ro','explorer_ro')
       OR (p.is_explorer AND pg_get_userbyid(p.grantee)='analyst_ro'))
UNION
SELECT s.nspname::text,'sandbox_acl_refused'::text FROM spaces s, pg_roles r
WHERE r.rolname IN (SELECT jsonb_array_elements_text(mdp.sandbox_policy()->'runtime_roles'))
  AND (pg_has_role(r.oid,to_regrole(s.owner_role),'MEMBER')
       -- showcase_wh inherits reviewed explorer reads. The ACL scan above still refuses
       -- every direct grant to it; inherited group reads must not block human sandbox DDL.
       OR (r.rolname<>'showcase_wh' AND (has_schema_privilege(r.oid,s.oid,'USAGE')
         OR EXISTS (SELECT 1 FROM pg_class c WHERE c.relnamespace=s.oid AND has_table_privilege(r.oid,c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')))));
$$;
REVOKE ALL ON FUNCTION mdp.sandbox_violations() FROM PUBLIC,service_read;

CREATE OR REPLACE FUNCTION mdp.guard_sandbox_access() RETURNS event_trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE caller name := coalesce(nullif(current_setting('role'),'none'),session_user);
  bad record; command record; policy jsonb := mdp.sandbox_policy();
BEGIN
  IF (SELECT rolsuper FROM pg_roles WHERE rolname=caller) THEN RETURN; END IF;
  -- Production DDL does not sweep scratch ACLs. Humans and grants on scratch
  -- objects are checked here; the separate worker catches historical ACL drift.
  IF NOT pg_has_role(caller,'analyst_ro','MEMBER') AND NOT pg_has_role(caller,'explorer_ro','MEMBER')
    AND NOT EXISTS (SELECT 1 FROM pg_event_trigger_ddl_commands() c
      LEFT JOIN pg_class rel ON c.classid='pg_class'::regclass AND c.objid=rel.oid
      JOIN pg_namespace n ON n.oid=CASE WHEN c.classid='pg_namespace'::regclass THEN c.objid ELSE rel.relnamespace END
      WHERE mdp.is_sandbox(n.nspname)) THEN RETURN; END IF;
  FOR command IN SELECT * FROM pg_event_trigger_ddl_commands() LOOP
    IF command.classid='pg_namespace'::regclass AND EXISTS (
      SELECT 1 FROM pg_namespace n LEFT JOIN mdp.sandbox_state s ON s.schema_name=n.nspname
      WHERE n.oid=command.objid AND mdp.is_sandbox(n.nspname) AND
        (s.schema_name IS NULL OR n.nspowner<>to_regrole(s.owner_role))) THEN
      RAISE EXCEPTION '%',policy->'messages'->>'sandbox_missing' USING ERRCODE='42501';
    END IF;
    IF command.classid IN ('pg_class'::regclass,'pg_proc'::regclass) THEN
      IF TG_TAG IN ('CREATE TABLE','CREATE TABLE AS','SELECT INTO','CREATE VIEW','CREATE MATERIALIZED VIEW','CREATE FOREIGN TABLE','ALTER TABLE') AND EXISTS (
        SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN mdp.sandbox_state s ON s.schema_name=n.nspname
        WHERE c.oid=command.objid AND (s.manual_frozen OR s.quota_frozen)) THEN
        RAISE EXCEPTION '%',policy->'messages'->>'sandbox_frozen' USING ERRCODE='42501';
      END IF;
      IF EXISTS (
        WITH RECURSIVE inputs(classid,oid) AS (
          SELECT command.classid,command.objid WHERE EXISTS (
            SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
              WHERE command.classid='pg_class'::regclass AND c.oid=command.objid AND mdp.is_sandbox(n.nspname) AND c.relkind IN ('v','m')
            UNION ALL
            SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
              WHERE command.classid='pg_proc'::regclass AND p.oid=command.objid AND mdp.is_sandbox(n.nspname))
          UNION
          SELECT d.refclassid,d.refobjid FROM inputs i
            LEFT JOIN pg_rewrite rw ON i.classid='pg_class'::regclass AND rw.ev_class=i.oid
            JOIN pg_depend d ON (d.classid=i.classid AND d.objid=i.oid) OR (d.classid='pg_rewrite'::regclass AND d.objid=rw.oid)
            WHERE d.refclassid IN ('pg_class'::regclass,'pg_proc'::regclass)
        ) SELECT 1 FROM inputs i JOIN pg_class c ON i.classid='pg_class'::regclass AND c.oid=i.oid JOIN pg_namespace n ON n.oid=c.relnamespace
          WHERE n.nspname IN ('raw','staging','intermediate') OR n.nspname LIKE 'explore\_%' OR n.nspname LIKE 'tenant\_%\_staging'
      ) THEN
        RAISE EXCEPTION '%',policy->'messages'->>'sandbox_view_refused' USING ERRCODE='42501';
      END IF;
    END IF;
  END LOOP;
  SELECT * INTO bad FROM mdp.sandbox_violations() LIMIT 1;
  IF FOUND THEN RAISE EXCEPTION '%',policy->'messages'->>bad.code USING ERRCODE='42501'; END IF;
END $$;
REVOKE ALL ON FUNCTION mdp.guard_sandbox_access() FROM PUBLIC,service_read;
DROP EVENT TRIGGER IF EXISTS mdp_sandbox_access;
CREATE EVENT TRIGGER mdp_sandbox_access ON ddl_command_end
  WHEN TAG IN ('GRANT','ALTER DEFAULT PRIVILEGES','CREATE SCHEMA','ALTER SCHEMA','ALTER TABLE',
               'CREATE TABLE','CREATE TABLE AS','SELECT INTO','CREATE VIEW','CREATE MATERIALIZED VIEW',
               'CREATE FUNCTION','ALTER FUNCTION','CREATE PROCEDURE','ALTER PROCEDURE','CREATE TYPE','ALTER TYPE','CREATE SEQUENCE','ALTER SEQUENCE','CREATE FOREIGN TABLE')
  EXECUTE FUNCTION mdp.guard_sandbox_access();

-- Grant existing schemas before parallel models create their first tables.
-- Table DDL must not rewrite a shared schema ACL.
DO $$ DECLARE s text; BEGIN
  FOR s IN SELECT nspname FROM pg_namespace
    WHERE nspname NOT LIKE 'pg\_%' AND nspname NOT LIKE 'wb\_%'
      AND nspname NOT IN ('information_schema','control','mdp','raw','catalog') LOOP
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO explorer_ro',s);
  END LOOP;
END $$;
-- Reconcile existing objects as well as future DDL. No raw payload grants to reader.
SELECT mdp.grant_warehouse_table(c.oid) FROM pg_class c
  JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname NOT LIKE 'pg\_%' AND n.nspname NOT IN ('information_schema','control','mdp');
-- An earlier rule granted reader_wh every tenant_* schema: revoke what it holds outside raw, marts and
-- tenant_*_marts, on the schema, its tables and their columns (a table revoke takes the column grants
-- with it), and every default privilege naming it anywhere.
DO $$ DECLARE s text; d record; BEGIN
  FOR s IN SELECT n.nspname FROM pg_namespace n
      WHERE n.nspname NOT IN ('raw','marts') AND n.nspname NOT LIKE 'tenant\_%\_marts'
        AND (EXISTS (SELECT 1 FROM aclexplode(n.nspacl) a WHERE a.grantee='reader_wh'::regrole)
          OR EXISTS (SELECT 1 FROM pg_class c, aclexplode(c.relacl) a
                     WHERE c.relnamespace=n.oid AND a.grantee='reader_wh'::regrole)
          OR EXISTS (SELECT 1 FROM pg_class c JOIN pg_attribute t ON t.attrelid=c.oid, aclexplode(t.attacl) a
                     WHERE c.relnamespace=n.oid AND a.grantee='reader_wh'::regrole)) LOOP
    EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA %I FROM reader_wh',s);
    EXECUTE format('REVOKE USAGE ON SCHEMA %I FROM reader_wh',s);
  END LOOP;
  FOR d IN SELECT pg_get_userbyid(p.defaclrole) AS owner, n.nspname AS schema, p.defaclobjtype AS kind
      FROM pg_default_acl p LEFT JOIN pg_namespace n ON n.oid=p.defaclnamespace, aclexplode(p.defaclacl) a
      WHERE a.grantee='reader_wh'::regrole LOOP
    EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE %I %s REVOKE ALL ON %s FROM reader_wh', d.owner,
      CASE WHEN d.schema IS NULL THEN '' ELSE format('IN SCHEMA %I', d.schema) END,
      CASE d.kind WHEN 'r' THEN 'TABLES' WHEN 'S' THEN 'SEQUENCES' WHEN 'f' THEN 'FUNCTIONS'
                  WHEN 'T' THEN 'TYPES' ELSE 'SCHEMAS' END);
  END LOOP;
END $$;
REVOKE ALL ON SCHEMA mdp, raw FROM analyst_ro, explorer_ro;
REVOKE ALL ON ALL TABLES IN SCHEMA raw FROM explorer_ro;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA mdp FROM PUBLIC, service_read, analyst_ro, explorer_ro;
COMMIT;
