export const round4Css = `
.split:has(>#recent-runs):not(:has(#run-chart)){grid-template-columns:1fr}.poster{align-items:stretch}.targets>.table-wrap{max-height:620px}.alert-detail{padding:12px 0;border-bottom:1px solid var(--line)}.alert-detail>strong{display:block;overflow-wrap:anywhere}.budget-spend{color:var(--foreground)}
.summary-strip a:hover{text-decoration:none;border-color:var(--teal);color:var(--teal)}
.function-grid{align-items:stretch!important}.function-card{display:flex;flex-direction:column;position:relative}.function-heading{padding-top:32px}.function-heading>.badge{position:absolute;right:22px;top:18px}.function-heading h2{overflow-wrap:anywhere;margin-bottom:4px}.function-card>p{margin:6px 0}.spark-slot{min-height:78px;display:flex;align-items:center;margin-top:auto}.spark-slot>*{width:100%}.function-card:hover{border-color:var(--teal);box-shadow:0 4px 16px color-mix(in srgb,var(--foreground) 10%,transparent);cursor:pointer}.function-card>a:last-child{margin-top:8px}.mini-spark .last-value{font-size:24px}.spark-empty{font-size:13px;color:var(--muted);padding:12px 0}
.grid:has(>#budgets){grid-template-columns:repeat(2,minmax(0,1fr))}#budgets{grid-column:1/-1;order:3}.budget-table{min-width:760px;width:100%}.budget-table td{padding:10px 12px;vertical-align:top}.budget-table td:first-child{min-width:170px}.budget-table td:nth-child(4){min-width:180px}.budget-table small{display:block;font-size:11px;margin-top:4px}.budget-table details{margin:0}.budget-table form{margin-top:12px;max-width:240px}.budget-table input{width:100%;min-width:0}.budget-row{padding:12px 0}.budget-row p{font-size:12px;margin:6px 0}.budget-row h3{margin-bottom:4px}.budget-meter{position:relative;height:8px;margin:9px 0}.budget-meter progress{display:block;width:100%;height:8px;appearance:none;border:0;border-radius:var(--radius);overflow:hidden;background:var(--line)}.budget-meter progress::-webkit-progress-bar{background:var(--line)}.budget-meter{--meter-fill:var(--teal)}.budget-meter.watch{--meter-fill:var(--warn)}.budget-meter.over{--meter-fill:var(--danger);outline:1px solid var(--danger);outline-offset:2px}.budget-meter progress::-webkit-progress-value{background:var(--meter-fill)}.budget-meter progress::-moz-progress-bar{background:var(--meter-fill)}.budget-meter.zero progress{box-shadow:inset 0 0 0 1px var(--muted)}.soft-tick{position:absolute;top:-3px;height:9px;border-left:1px solid var(--warn)}.budget-meter.zero .soft-tick{height:6px}
.receipt-group>summary,.receipt-detail>summary{color:var(--muted);font-weight:400}.receipt-group.has-rejected{background:color-mix(in srgb,var(--warn) 6%,transparent)}.receipt-count{color:var(--teal);font-weight:650}.has-rejected .receipt-count{color:var(--warn)}.receipt-detail strong{font-weight:650}.receipt-group .receipt-detail{padding-left:12px}
.first-run .eyebrow{font-size:12px}.first-run button{background:white;color:var(--teal-dark);border-color:white;padding:10px 20px}.first-run button:hover{background:var(--paper)}.retry-button{padding:8px 12px;border-radius:var(--radius);display:inline-block}.retry-button:hover{color:white}.delivery-link{padding:10px 0;border-bottom:1px solid var(--line)}.delivery-link:hover{text-decoration:none;background:var(--paper)}
.live-dot{display:inline-block;height:6px;width:6px;border-radius:50%;background:var(--teal);animation:live-pulse 1.6s ease-in-out infinite;margin-right:6px}.live-controls{display:flex;gap:8px;align-items:center}.live-controls button{padding:3px 6px;font-size:11px}.run-swap{animation:card-fade .16s ease-out}@keyframes live-pulse{50%{opacity:.25}}@keyframes card-fade{from{opacity:.15}to{opacity:1}}
.target-tools{grid-template-columns:minmax(100px,1fr) auto auto auto auto}.draft-note{font-size:12px;color:var(--muted)}
.grid:has(>#budgets)>section{height:100%}@media(max-width:850px){.grid:has(>#budgets){grid-template-columns:1fr}}@media(max-width:650px){.target-tools{grid-template-columns:1fr 1fr}.targets table,.targets tbody{display:block}.targets thead{display:block}.targets thead tr{display:block}.targets th{display:none}.targets th:first-child{display:block}.targets tbody tr{display:grid;grid-template-columns:auto 1fr;gap:0;padding:10px 0;border-bottom:1px solid var(--line)}.targets td{border:0;padding:3px 4px;white-space:normal;max-width:none}.targets td:first-child{grid-column:1/-1}.targets td:nth-child(3){display:none}.targets td:last-child{grid-column:2}.targets td:first-child{display:flex;align-items:center;gap:5px;flex-wrap:nowrap}.targets td:first-child .copy{display:none}.targets td form:has([name=platform_account_id]){display:none}.targets td .row{flex-wrap:nowrap;justify-content:space-between}.targets td form{flex-wrap:nowrap}.targets td form input{min-width:0;max-width:145px}.targets .table-hint{display:none!important}.target-handle{max-width:160px}.first-run{padding:24px}.function-heading h2{font-size:17px}}
.count-warn,.summary-strip .count-warn,.poster .count-warn{color:var(--warn)}.count-danger,.summary-strip .count-danger,.poster .count-danger{color:var(--danger)}.count-muted,.summary-strip .count-muted,.poster .count-muted{color:var(--muted)}.badge.rejected{background:color-mix(in srgb,var(--warn) 12%,white);color:var(--warn)}.invalid-import{background:color-mix(in srgb,var(--warn) 8%,white)}
.empty,.spark-empty,.first-run{text-align:center}.first-run p{margin-left:auto;margin-right:auto}.first-run form{justify-content:center}.empty-heading{justify-content:center;text-align:center}.empty-heading h2{flex-basis:100%}
@media(prefers-reduced-motion:reduce){.live-dot,.run-swap{animation:none}}
`;
