// Use declared result types so numeric strings and null-only columns align consistently.
export const isNumericType=(type:string)=>/^(?:smallint|integer|bigint|int[248]?|tinyint|mediumint|float[48]?|double(?: precision)?|real|numeric|decimal|number|money|smallserial|serial|bigserial)(?:\s*\(|$)/i.test(type.trim());
export const changedFiles=(diff:string)=>[...new Set([...diff.matchAll(/^\+\+\+ ([^\t\r\n]+)/gm)].map(match=>match[1]!.replace(/^b\//,'')).filter(path=>path!=='/dev/null'))];
export const bareModel=(value:string)=>value.replace(/^(?:model|source)\.[^.]+\./,'').replace(/^marts\./,'');
export const rowLabel=(count:number,truncated?:boolean,totalRows?:number)=>totalRows!==undefined?`${Math.min(count,100)} of ${totalRows.toLocaleString("en-US")} rows`:truncated?`First ${Math.min(count,100)} rows · total unavailable`:count>100?`100 of ${count.toLocaleString('en-US')} rows`:`${count} ${count===1?'row':'rows'}`;
export const workbenchCss=`
.wb .result-hint{padding:0 0 10px}.wb table th{padding:13px 16px;font-weight:700;box-shadow:inset 0 -2px var(--line);z-index:1}.wb table th button{color:var(--muted)}.wb table td{padding:11px 16px;border-bottom:1px solid color-mix(in srgb,var(--line) 65%,transparent)}.wb tbody tr:nth-child(even){background:color-mix(in srgb,var(--paper) 55%,transparent)}.wb tbody tr:hover{background:color-mix(in srgb,var(--teal) 7%,transparent)}.wb table .numeric{text-align:right;font-variant-numeric:tabular-nums}.wb .terminal-card.error .copy{color:var(--muted);background:var(--paper);border-color:var(--line)}
.wb .workspace{align-items:start}.wb .history{align-self:start;max-height:520px}.wb .history .history-entry{padding:12px;display:block}.wb .history-name{display:inline-flex;align-items:baseline;gap:7px}.wb .history-name .status-dot{flex:0 0 6px;margin:0}.wb .history-entry[aria-current=page]{background:color-mix(in srgb,var(--teal) 8%,var(--paper));font-weight:600}.wb .history-entry:hover{text-decoration:none;background:var(--paper)}.wb .history-entry:hover small{color:var(--foreground)}.wb .history .history-footer{display:inline;padding:0;border:0}.wb .history .empty{padding:22px 12px;margin:20px 0}.wb .history .empty p{margin-bottom:0}.status-dot{display:inline-block;width:6px;height:6px;border-radius:50%;margin-right:7px;background:var(--muted)}.status-dot.succeeded{background:var(--teal)}.status-dot.failed{background:var(--danger)}.status-dot.running,.status-dot.queued{background:var(--warn)}
.wb .result-top{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:24px;align-items:start;margin-bottom:18px}.wb .result-top form{display:flex;flex-direction:column;align-items:stretch;gap:8px;min-width:160px}.wb .result-top h2{margin-bottom:8px}.wb .result-top .caption{line-height:2}.wb .result-grid{display:grid;grid-template-columns:minmax(0,1fr);gap:18px;align-items:start}.wb .result-grid:has(.inspector:not([hidden])){grid-template-columns:minmax(0,1fr) 280px}.wb .result-data{min-width:0}.wb .inspector{position:static;width:auto;max-width:none;height:auto;box-shadow:none;border-radius:var(--radius);background:var(--paper);padding:18px;animation:reveal .16s ease-out;max-height:none}.wb .inspector dd:last-child{margin-bottom:0}.wb .inspector .row{flex-wrap:nowrap;align-items:start}.wb .inspector h2{overflow-wrap:anywhere}.wb .inspector h2,.wb .inspector dd{font-size:13px}.wb .inspector p{margin:4px 0}.wb th button{padding:6px;border-radius:4px;margin:-6px}.wb th button:hover,.wb th button[aria-expanded=true]{background:color-mix(in srgb,var(--teal) 12%,white);color:var(--teal-dark)}
.wb tbody tr.added-row{background:color-mix(in srgb,var(--teal) 7%,transparent)}.wb .removed-row{color:var(--muted);opacity:.7}.wb .inspector-extreme{white-space:nowrap;overflow:auto;overflow-wrap:normal}.wb .changed-row{color:var(--foreground)}.wb tbody tr.changed-row{background:color-mix(in srgb,var(--warn) 6%,transparent)}.wb td.changed-cell{background:color-mix(in srgb,var(--warn) 10%,white)}.wb .changed-row:hover{background:var(--paper)}.wb td{max-width:280px}.wb .cell-value{min-width:0;width:240px;max-width:240px;margin:0}.wb .cell-value summary{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--foreground);font-weight:400}.wb .cell-value summary::after{content:' ↗'}.wb .cell-value p{white-space:normal;overflow-wrap:anywhere}.wb .cell-value[open] summary{color:var(--teal)}
.wb button:active{transform:translateY(2px);box-shadow:inset 0 2px 3px color-mix(in srgb,var(--foreground) 30%,transparent)}.wb .copy:hover{background:color-mix(in srgb,var(--teal) 8%,white);border-color:var(--teal);color:var(--teal)}.wb kbd{font:10px/1.5 system-ui,sans-serif;opacity:1;border:1px solid currentColor;border-radius:3px;padding:1px 3px;margin-left:3px}.wb .running-strip{position:sticky;top:0;z-index:15;background:var(--teal-dark);color:white;border-radius:var(--radius);padding:10px 16px;margin-bottom:18px;display:flex;justify-content:space-between;align-items:center;gap:10px;font-size:13px}.wb .running-strip .heartbeat{background:white}.wb .running-strip button{padding:4px 10px}.wb #build{scroll-margin-top:65px}.wb .model-label{display:inline-block;margin-right:10px}.wb .cycle-notice{font-size:12px;padding:10px 14px;border:1px solid color-mix(in srgb,var(--teal) 35%,var(--line));border-radius:var(--radius);background:color-mix(in srgb,var(--teal) 5%,var(--paper))}.wb #wb-ticket{scroll-margin-top:65px}.wb{--build-reserve:clamp(320px,65vh,620px)}.wb .building-card{min-height:var(--build-reserve)}.wb .terminal-card{min-height:0;padding:24px}main:has(.wb-landing)>h1{text-align:center}.wb-landing{display:grid;place-items:center;text-align:center;padding:32px}.wb .pr-review{scroll-margin-top:65px}.wb .explain-return{display:inline-block;margin-top:16px}.wb-landing>div{max-width:580px}.wb-landing form{justify-content:center}.wb .added-kind{color:var(--teal);font-weight:650}
@media(max-width:850px){.wb .result-grid:has(.inspector:not([hidden])){grid-template-columns:minmax(0,1fr)}.wb .inspector{position:fixed;z-index:30;top:auto;bottom:16px;left:16px;right:16px;width:auto;max-height:45vh;overflow:auto;box-shadow:0 8px 30px color-mix(in srgb,var(--foreground) 20%,transparent)}.wb #builder>.tools:has([data-build-action]){display:grid;grid-template-columns:1fr 1fr}.wb #builder [data-build-action]{width:100%}.wb #builder [data-build-action] kbd{display:block;width:fit-content;margin:4px auto 0;font-size:9px}.wb .result-top{grid-template-columns:minmax(0,1fr);gap:12px}.wb .result-top form{flex-direction:row;flex-wrap:wrap}.wb .running-strip{font-size:12px}.wb .running-strip strong{overflow-wrap:anywhere}.wb .history{max-height:260px}}
@media(prefers-reduced-motion:reduce){.wb .inspector{animation:none}}
.wb .lineage{margin:0 0 18px;border:1px solid color-mix(in srgb,var(--teal) 35%,var(--line));border-radius:var(--radius);padding:14px;background:var(--card,var(--paper));min-width:0}
.wb .lineage figcaption{display:flex;justify-content:space-between;gap:12px;align-items:baseline;flex-wrap:wrap}
.wb .lineage-heading{display:flex;align-items:baseline;flex-wrap:wrap;gap:4px 12px;min-width:0;flex:1 1 240px}
.wb .lineage-heading strong{font-size:14px;font-weight:650;color:var(--foreground);overflow-wrap:anywhere}
.wb .lineage-actions{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap;min-width:0;font-size:12px}
.wb .lineage-runs{margin:0;max-width:100%}.wb .lineage-runs summary{border:1px solid var(--line);border-radius:var(--radius);padding:3px 8px;font-size:12px;font-weight:400}.wb .lineage-runs ul{list-style:none;padding:0;margin:8px 0;display:grid;gap:6px;overflow-wrap:anywhere}
.wb .nodes{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.wb .node{border:1px solid var(--line);border-radius:10px;padding:8px 10px;min-width:100px;max-width:100%;flex:0 1 auto}.wb .node.source{background:color-mix(in srgb,var(--teal) 8%,var(--paper))}.wb .node.model{background:var(--paper)}
.wb .node-name{display:flex;align-items:baseline;gap:6px;font-size:13px;color:var(--foreground);margin-bottom:3px;min-width:0}.wb .node-name>span:not(.lineage-freshness){overflow-wrap:anywhere;min-width:0}.wb .node-name svg{flex:0 0 12px;opacity:.6;align-self:center}.wb .node.more{display:flex;align-items:center}
.wb .column-share{display:block;height:2px;margin-top:6px;background:var(--teal)}.wb .lineage .lineage-downstream{margin:10px 0 0}.wb .lineage .lineage-empty{margin:12px 0 0;text-align:center}
.wb .lineage-freshness{display:inline-flex;flex:0 0 auto;align-items:center;color:var(--teal)}.wb .lineage-freshness.unknown{color:var(--muted)}.wb .lineage-freshness time,.wb .lineage-freshness>span{font-size:0;white-space:normal}.wb .lineage-freshness time::before,.wb .lineage-freshness>span::before{content:'';display:inline-block;width:6px;height:6px;border-radius:50%;background:currentColor}
.wb .lineage-facts{display:flex;align-items:baseline;flex-wrap:wrap;gap:6px 12px}.wb .lineage-heading{align-items:center}.wb .result-file{display:inline-flex;align-items:center;font-size:12px}
.wb .nodes>.pop{max-width:100%;flex:0 1 auto}.wb .nodes>.pop>.pop-trigger{display:flex;text-decoration:none;min-width:0}.wb .node{display:block;width:100%}.wb .node-name{align-items:flex-start}.wb .node-name>.entity{flex:1}.wb .node-name>svg{align-self:flex-start;margin-top:2px}.wb .node .caption{display:block;margin-top:6px}.wb .nodes>.pop:hover .node,.wb .nodes>.pop:focus-within .node{border-color:var(--teal)}
.wb .nodes .pop-body{max-width:min(300px,calc(100vw - 90px));overflow-wrap:anywhere}.wb .nodes .pop-head{align-items:flex-start}.wb .nodes .pop-head strong{min-width:0}.wb .nodes .pop-fact{flex-wrap:wrap}.wb .nodes .pop-col{gap:8px}.wb .nodes .pc-name{min-width:0;overflow-wrap:anywhere}.wb .lineage .schema{margin-bottom:0}.wb .lineage .schema-table th,.wb .lineage .schema-table td{padding:9px 10px}.wb .lineage .schema-table th{box-shadow:none}
.wb-landing{padding:48px 24px}.wb-landing>div{width:100%;max-width:820px}.wb-landing h2{font-size:24px;letter-spacing:-.5px}.wb-landing p{color:var(--muted);line-height:1.7;margin:12px 0 24px}.wb-jumpoffs{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:0 0 24px}.wb-jumpoffs form{display:flex;min-width:0}.wb-jumpoffs button{width:100%;padding:20px 16px;text-align:left;background:var(--paper);border:1px solid var(--line);border-radius:var(--card-radius);white-space:normal}.wb-jumpoffs button strong{display:flex;justify-content:space-between;gap:8px;font-size:14px;color:var(--foreground)}.wb-jumpoffs button>span{display:block;font-size:12px;font-weight:400;color:var(--muted);margin-top:8px;line-height:1.5}.wb-jumpoffs button:hover{border-color:var(--teal);background:color-mix(in srgb,var(--teal) 6%,var(--paper))}.wb-jumpoffs button:focus-visible{outline:2px solid var(--teal);outline-offset:3px}.wb #wb-models,.wb #wb-sql{scroll-margin-top:85px}
@media(max-width:650px){.wb-jumpoffs{grid-template-columns:minmax(0,1fr);gap:10px}.wb-landing{padding:28px 18px}.wb-landing h2{font-size:21px}.wb-jumpoffs button{padding:16px}.wb .nodes>.pop{flex-basis:100%}.wb .nodes>.pop>.pop-trigger{width:100%}.wb .nodes .pop-body{left:0;right:auto}.wb .lineage .schema-peek{display:none}}
@media(max-width:450px){.wb .lineage-heading .caption{flex-basis:100%}.wb .node{flex:1 1 100px}.wb .lineage-actions{width:100%}}

`;
export const workbenchScript=`document.addEventListener('DOMContentLoaded',()=>{
const root=document.querySelector('.wb');if(!root)return;const editor=root.querySelector('[name=sql]');
if(location.hash==='#wb-sql')editor?.focus();if(location.hash==='#wb-models')root.querySelector('[name=startingModel]')?.focus();
root.querySelectorAll('[data-insert]').forEach(select=>select.addEventListener('change',()=>{if(!select.value)return;const parts=select.value.split('.');const expression=select.dataset.insert==='ref'?"{{ ref('"+select.value+"') }}":"{{ source('"+parts[0]+"', '"+parts[1]+"') }}";editor.setRangeText(expression,editor.selectionStart,editor.selectionEnd,'end');editor.focus();select.value=''}));
root.addEventListener('click',e=>{if(e.target.closest('[data-edit-sql]')){editor.focus();editor.scrollIntoView({block:'center'})}});
const closeInspectors=()=>{root.querySelectorAll('.inspector').forEach(aside=>aside.hidden=true);root.querySelectorAll('[data-inspect]').forEach(button=>button.setAttribute('aria-expanded','false'))};
root.addEventListener('keydown',e=>{if(e.key==='Escape')closeInspectors();if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();const action=e.altKey?'backtest':e.shiftKey?'preview':'query';const button=root.querySelector('[value='+action+']');if(button&&!button.disabled)button.form.requestSubmit(button)}});
document.addEventListener('click',e=>{const button=e.target.closest('[data-inspect]');if(button){closeInspectors();root.querySelector('#'+button.dataset.inspect).hidden=false;button.setAttribute('aria-expanded','true')}else if(e.target.closest('[data-close-inspector]')||!e.target.closest('.inspector'))closeInspectors()});
let sending=false;root.addEventListener('submit',e=>{if(sending){e.preventDefault();return}sending=true;setTimeout(()=>root.querySelectorAll('[data-build-action]').forEach(button=>button.disabled=true),0)});
const ticket=root.querySelector('#wb-ticket');if(ticket?.dataset.land==='true')(root.querySelector('#pr-review')||ticket).scrollIntoView({block:'start'});
const retire=()=>{const strip=root.querySelector('[data-terminal]');if(strip)setTimeout(()=>strip.hidden=true,6000)};retire();
const tick=()=>root.querySelectorAll('[data-elapsed]').forEach(el=>{el.textContent=Math.max(0,Math.floor((Date.now()-Number(el.dataset.started))/1000))+'s'+(el.closest('.ticket')?' elapsed':'')});tick();
const initial=root.querySelector('[data-live-run]');
if(initial){const url=new URL(location.href);url.searchParams.set('runId',root.querySelector('[data-poll] [name=runId]').value);history.replaceState(null,'',url);root.querySelector('section[role=status]').scrollIntoView({block:'start'});
const elapsedTimer=setInterval(tick,1000);
const poll=async()=>{if(sending)return;try{const response=await fetch(url,{credentials:'same-origin'});if(!response.ok)throw Error();const doc=new DOMParser().parseFromString(await response.text(),'text/html');for(const id of ['wb-ticket','wb-running-strip']){const current=root.querySelector('#'+id),next=doc.getElementById(id);if(current&&next)current.replaceWith(next)}tick();if(root.querySelector('[data-live-run]'))setTimeout(poll,3000);else{clearInterval(elapsedTimer);if(!document.activeElement?.matches('textarea,input,select'))root.querySelector('#wb-ticket').scrollIntoView({block:'start'});retire();root.querySelectorAll('.history-entry').forEach(entry=>{const latest=[...doc.querySelectorAll('.history-entry')].find(item=>item.getAttribute('href')===entry.getAttribute('href'));if(latest){entry.querySelector('small').textContent=latest.querySelector('small').textContent;entry.querySelector('.status-dot').className=latest.querySelector('.status-dot').className}});root.querySelectorAll('[data-build-action],[value=load]').forEach(button=>button.disabled=false);if(typeof overflowHints==='function')overflowHints()}}catch{const label=root.querySelector('[data-poll]')?.previousElementSibling;if(label)label.textContent='Connection interrupted · retrying';setTimeout(poll,3000)}};setTimeout(poll,3000)
}
});`;
