testthat::test_that("features preserve grain and rights and training is learnable", {
  db <- Sys.getenv("MDP_DB")
  if (!nzchar(db)) testthat::skip("MDP_DB is unset; database fixture tests require a service or snapshot")
  con <- tryCatch(mdpr::mdp_connect(db), error = function(e) NULL)
  if (is.null(con)) testthat::skip("MDP_DB cannot connect; start the local fixture stack")
  on.exit(DBI::dbDisconnect(con), add = TRUE)
  source(testthat::test_path("../../R/features.R"), local = TRUE)
  x <- dplyr::collect(features(con))
  testthat::expect_gt(nrow(x), 0L)
  testthat::expect_equal(anyDuplicated(x[c("chart_name", "chart_week", "chart_position")]), 0L)
  testthat::expect_identical(mdpr::mdp_check_rights(x), x)
  train <- mdpr::mdp_learnable(x)
  testthat::expect_true(all(!is.na(train$learning_eligible) & train$learning_eligible))
})
