#!/usr/bin/env python3
"""Generate the analyst inventory from the same meta.grain contracts as the SDK."""

import argparse
import json
from pathlib import Path

import yaml
from mdp_functions.sandbox_policy import POLICY

ROOT = Path(__file__).resolve().parents[1]
START = "<!-- analyst-contracts:start -->"
END = "<!-- analyst-contracts:end -->"


def contracts():
    rows = []
    for path in sorted((ROOT / "dbt/models/marts").rglob("*.yml")):
        for model in yaml.safe_load(path.read_text()).get("models", []):
            meta = model.get("config", {}).get("meta", {})
            grain = meta.get("grain")
            if not grain:
                continue
            tenant = meta.get("tenant_scoped", "tenant" in path.parts)
            schema = "tenant_<slug>_marts" if tenant else "marts"
            columns = [
                {
                    key: column.get(key, "")
                    for key in ("name", "data_type", "description")
                }
                for column in model["columns"]
            ]
            rows.append(
                {
                    "relation": f"{schema}.{model['name']}",
                    "schema": schema,
                    "name": model["name"],
                    "access": "excluded" if tenant else "select",
                    "grain": grain,
                    "columns": columns,
                    "rights_columns": [
                        c["name"]
                        for c in columns
                        if c["name"]
                        in ("learning_eligible", "resale_permitted", "source_keys")
                    ],
                    "contract": str(path.relative_to(ROOT)),
                }
            )
    return sorted(rows, key=lambda row: row["relation"])


def inventory(relations):
    rows = []
    for row in relations:
        keys = [
            c["name"]
            for c in row["columns"]
            if c["name"] not in row["grain"]
            and (c["name"].endswith(("_id", "_key", "_gid")) or c["name"] == "isrc")
            and not c["name"].startswith("_")
        ]
        rows.append(
            (
                row["name"],
                row["access"] == "excluded",
                row["grain"],
                keys,
                row["contract"],
            )
        )
    rows.sort()
    accessible = sum(not row[1] for row in rows)
    lines = [
        START,
        "<!-- Generated by: uv run --project functions python ops/analyst-doc.py -->",
        (
            f"{len(rows)} served contracts: {accessible} global mart contracts permit analyst reads when built; "
            f"{len(rows) - accessible} tenant marts excluded."
        ),
        "",
        "Grain is the composite row key; retain every grain column when joining or deduplicating.",
        "",
        "| Mart / contract | Access | Grain | Other key columns |",
        "|---|---|---|---|",
    ]
    for name, tenant, grain, keys, path in rows:
        code = lambda values: ", ".join(f"`{v}`" for v in values) or "—"
        schema = "tenant_<slug>_marts" if tenant else "marts"
        lines.append(
            f"| [`{schema}.{name}`](../{path}) | "
            f"{'Excluded' if tenant else 'SELECT'} | {code(grain)} | {code(keys)} |"
        )
    return "\n".join([*lines, END])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "docs/analyst-access.md"
    current = path.read_text()
    before, rest = current.split(START)
    _, after = rest.split(END)
    relations = contracts()
    expected = before + inventory(relations) + after
    local_start, local_end = "<!-- local-marts:start -->", "<!-- local-marts:end -->"
    local_names = sorted(
        name
        for name in (ROOT / "ops/local/models.txt").read_text().splitlines()
        if name.startswith("mart_")
    )
    assert set(local_names) <= {
        row["name"] for row in relations if row["access"] == "select"
    }
    local_block = "\n".join(
        [
            local_start,
            "<!-- Generated by: uv run --project functions python ops/analyst-doc.py -->",
            "The local week builds these marts and checks analyst access before startup finishes:",
            "",
            *[f"- `marts.{name}`" for name in local_names],
            "",
            "The list comes from [models.txt](../ops/local/models.txt). Run `bash ops/local/up.sh` to build it.",
            local_end,
        ]
    )
    updates = {
        path: expected,
        ROOT / "docs/DEVELOPING.md": (ROOT / "docs/DEVELOPING.md").read_text(),
    }
    for document, content in updates.items():
        prefix, rest = content.split(local_start)
        _, suffix = rest.split(local_end)
        updates[document] = prefix + local_block + suffix
    expected = updates[path]
    metadata = ROOT / "r/mdpr/inst/extdata/contracts.json"
    expected_json = (
        json.dumps(
            {"format": 1, "relations": relations, "sandbox": POLICY},
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )
    if args.check:
        if (
            any(
                document.read_text() != content for document, content in updates.items()
            )
            or not metadata.exists()
            or metadata.read_text() != expected_json
        ):
            raise SystemExit(
                "analyst inventory stale: run uv run --project functions python ops/analyst-doc.py"
            )
        print("PASS analyst contract inventory")
    else:
        for document, content in updates.items():
            document.write_text(content)
        metadata.parent.mkdir(parents=True, exist_ok=True)
        metadata.write_text(expected_json)


if __name__ == "__main__":
    main()
