#!/usr/bin/env python3
"""Generate the shared label catalog. Run dbt parse first; --check is read-only."""

import argparse
import json
from pathlib import Path

from mdp_functions.relation_labels import generate
from mdp_functions.settings import REPO

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--manifest", type=Path, default=REPO / "dbt/target/manifest.json")
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
values = generate(json.loads(args.manifest.read_text()))
encoded = json.dumps(values, indent=2, sort_keys=True) + "\n"
outputs = {
    REPO / "functions/src/mdp_functions/relation_labels.json": encoded,
    REPO
    / "control/packages/data-sdk/src/relation-labels.generated.ts": "// Generated by ops/label-catalog.py. Do not edit.\nexport const relationLabels: Record<string, Record<string, unknown>> = "
    + encoded.rstrip()
    + ";\n",
    REPO
    / "ops/fly/postgres/boot/init/16-label-definitions.sql": "-- Generated by ops/label-catalog.py. Do not edit.\nTRUNCATE catalog.label_definitions;\n"
    + "\n".join(
        "INSERT INTO catalog.label_definitions VALUES ('"
        + key.replace("'", "''")
        + "', '"
        + json.dumps(value, sort_keys=True).replace("'", "''")
        + "'::jsonb);"
        for key, value in values.items()
    )
    + "\nSELECT catalog.refresh_labels();\n",
}
for path, content in outputs.items():
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(
                f"Label drift: run uv run --project functions python ops/label-catalog.py ({path.name})"
            )
    else:
        path.write_text(content)
print(f"PASS {len(values)} relation labels match the dbt manifest")
